// Translation dictionary for the site's UI chrome (nav, header, footer,
// cart, checkout, orders, auth, notifications, common buttons/messages).
// Deliberately does NOT cover the ~800 real product names/descriptions in
// the catalogue - those are actual business content pulled from
// Firestore/data/products.js, and machine-generating translations for real
// products across 5 languages would be inaccurate and worse than leaving
// them as-is. The admin panel exposes per-language fields (Products/
// Categories pages) so real, reviewed translations can be entered over
// time instead.
export const LANGUAGES = [
  { code: 'en', label: 'English' },
  { code: 'ta', label: 'தமிழ்' },
  { code: 'hi', label: 'हिन्दी' },
  { code: 'ml', label: 'മലയാളം' },
  { code: 'te', label: 'తెలుగు' },
  { code: 'kn', label: 'ಕನ್ನಡ' },
];

const nav = {
  en: { plants: 'Plants', seeds: 'Seeds', potsPlanters: 'Pots & Planters', plantCare: 'Plant Care', landscaping: 'Landscaping', gifting: 'Gifting', b2bSales: 'B2B Sales', gardenServices: 'Garden Services', blog: 'Blog', offers: 'Offers', locateStore: 'Locate Store' },
  ta: { plants: 'செடிகள்', seeds: 'விதைகள்', potsPlanters: 'தொட்டிகள் மற்றும் பாட்ஸ்', plantCare: 'செடி பராமரிப்பு', landscaping: 'லேண்ட்ஸ்கேப்பிங்', gifting: 'பரிசுகள்', b2bSales: 'B2B விற்பனை', gardenServices: 'தோட்ட சேவைகள்', blog: 'வலைப்பதிவு', offers: 'சலுகைகள்', locateStore: 'கடை கண்டறிக' },
  hi: { plants: 'पौधे', seeds: 'बीज', potsPlanters: 'गमले और प्लांटर', plantCare: 'पौधों की देखभाल', landscaping: 'लैंडस्केपिंग', gifting: 'उपहार', b2bSales: 'B2B बिक्री', gardenServices: 'बागवानी सेवाएं', blog: 'ब्लॉग', offers: 'ऑफ़र', locateStore: 'स्टोर खोजें' },
  ml: { plants: 'ചെടികൾ', seeds: 'വിത്തുകൾ', potsPlanters: 'ചട്ടികളും പ്ലാന്ററുകളും', plantCare: 'ചെടി പരിചരണം', landscaping: 'ലാൻഡ്സ്കേപ്പിംഗ്', gifting: 'സമ്മാനങ്ങൾ', b2bSales: 'B2B വിൽപ്പന', gardenServices: 'തോട്ട സേവനങ്ങൾ', blog: 'ബ്ലോഗ്', offers: 'ഓഫറുകൾ', locateStore: 'സ്റ്റോർ കണ്ടെത്തുക' },
  te: { plants: 'మొక్కలు', seeds: 'విత్తనాలు', potsPlanters: 'కుండలు & ప్లాంటర్లు', plantCare: 'మొక్కల సంరక్షణ', landscaping: 'ల్యాండ్‌స్కేపింగ్', gifting: 'బహుమతులు', b2bSales: 'B2B అమ్మకాలు', gardenServices: 'తోట సేవలు', blog: 'బ్లాగ్', offers: 'ఆఫర్లు', locateStore: 'స్టోర్ కనుగొనండి' },
  kn: { plants: 'ಸಸ್ಯಗಳು', seeds: 'ಬೀಜಗಳು', potsPlanters: 'ಪಾಟ್‌ಗಳು ಮತ್ತು ಪ್ಲಾಂಟರ್‌ಗಳು', plantCare: 'ಸಸ್ಯ ಆರೈಕೆ', landscaping: 'ಲ್ಯಾಂಡ್‌ಸ್ಕೇಪಿಂಗ್', gifting: 'ಉಡುಗೊರೆಗಳು', b2bSales: 'B2B ಮಾರಾಟ', gardenServices: 'ತೋಟ ಸೇವೆಗಳು', blog: 'ಬ್ಲಾಗ್', offers: 'ಆಫರ್‌ಗಳು', locateStore: 'ಅಂಗಡಿ ಹುಡುಕಿ' },
};

const search = {
  en: { placeholders: ['Search plants...', 'Search seeds...', 'Search pots & planters...', 'Search plant care...', 'Search gifting...'], ariaLabel: 'Search plants, pots, seeds', micSearch: 'Search by voice', micListening: 'Listening... click to stop', micDenied: 'Microphone access denied.', micError: "Couldn't hear that - try again." },
  ta: { placeholders: ['செடிகளை தேடுங்கள்...', 'விதைகளை தேடுங்கள்...', 'தொட்டிகளை தேடுங்கள்...', 'செடி பராமரிப்பு தேடுங்கள்...', 'பரிசுகளை தேடுங்கள்...'], ariaLabel: 'செடிகள், தொட்டிகள், விதைகளை தேடுங்கள்', micSearch: 'குரல் மூலம் தேடுக', micListening: 'கேட்கிறது... நிறுத்த கிளிக் செய்யவும்', micDenied: 'மைக்ரோஃபோன் அணுகல் மறுக்கப்பட்டது.', micError: 'கேட்க முடியவில்லை - மீண்டும் முயற்சிக்கவும்.' },
  hi: { placeholders: ['पौधे खोजें...', 'बीज खोजें...', 'गमले खोजें...', 'पौध देखभाल खोजें...', 'उपहार खोजें...'], ariaLabel: 'पौधे, गमले, बीज खोजें', micSearch: 'आवाज़ से खोजें', micListening: 'सुन रहा है... रोकने के लिए क्लिक करें', micDenied: 'माइक्रोफ़ोन एक्सेस अस्वीकृत।', micError: 'सुन नहीं पाया - फिर से प्रयास करें।' },
  ml: { placeholders: ['ചെടികൾ തിരയുക...', 'വിത്തുകൾ തിരയുക...', 'ചട്ടികൾ തിരയുക...', 'ചെടി പരിചരണം തിരയുക...', 'സമ്മാനങ്ങൾ തിരയുക...'], ariaLabel: 'ചെടികൾ, ചട്ടികൾ, വിത്തുകൾ തിരയുക', micSearch: 'ശബ്ദത്തിലൂടെ തിരയുക', micListening: 'കേൾക്കുന്നു... നിർത്താൻ ക്ലിക്ക് ചെയ്യുക', micDenied: 'മൈക്രോഫോൺ ആക്സസ് നിരസിച്ചു.', micError: 'കേൾക്കാൻ കഴിഞ്ഞില്ല - വീണ്ടും ശ്രമിക്കുക.' },
  te: { placeholders: ['మొక్కలను వెతకండి...', 'విత్తనాలను వెతకండి...', 'కుండలను వెతకండి...', 'మొక్కల సంరక్షణ వెతకండి...', 'బహుమతులను వెతకండి...'], ariaLabel: 'మొక్కలు, కుండలు, విత్తనాలు వెతకండి', micSearch: 'వాయిస్ ద్వారా వెతకండి', micListening: 'వింటోంది... ఆపడానికి క్లిక్ చేయండి', micDenied: 'మైక్రోఫోన్ యాక్సెస్ నిరాకరించబడింది.', micError: 'వినడం సాధ్యం కాలేదు - మళ్ళీ ప్రయత్నించండి.' },
  kn: { placeholders: ['ಸಸ್ಯಗಳನ್ನು ಹುಡುಕಿ...', 'ಬೀಜಗಳನ್ನು ಹುಡುಕಿ...', 'ಪಾಟ್‌ಗಳನ್ನು ಹುಡುಕಿ...', 'ಸಸ್ಯ ಆರೈಕೆ ಹುಡುಕಿ...', 'ಉಡುಗೊರೆಗಳನ್ನು ಹುಡುಕಿ...'], ariaLabel: 'ಸಸ್ಯಗಳು, ಪಾಟ್‌ಗಳು, ಬೀಜಗಳನ್ನು ಹುಡುಕಿ', micSearch: 'ಧ್ವನಿಯ ಮೂಲಕ ಹುಡುಕಿ', micListening: 'ಕೇಳುತ್ತಿದೆ... ನಿಲ್ಲಿಸಲು ಕ್ಲಿಕ್ ಮಾಡಿ', micDenied: 'ಮೈಕ್ರೊಫೋನ್ ಪ್ರವೇಶ ನಿರಾಕರಿಸಲಾಗಿದೆ.', micError: 'ಕೇಳಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ - ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.' },
};

const header = {
  en: { account: 'Account', wishlist: 'Wishlist', cart: 'Cart', notifications: 'Notifications', language: 'Language' },
  ta: { account: 'கணக்கு', wishlist: 'விருப்பப்பட்டியல்', cart: 'கார்ட்', notifications: 'அறிவிப்புகள்', language: 'மொழி' },
  hi: { account: 'खाता', wishlist: 'विशलिस्ट', cart: 'कार्ट', notifications: 'सूचनाएं', language: 'भाषा' },
  ml: { account: 'അക്കൗണ്ട്', wishlist: 'വിഷ്‌ലിസ്റ്റ്', cart: 'കാർട്ട്', notifications: 'അറിയിപ്പുകൾ', language: 'ഭാഷ' },
  te: { account: 'ఖాతా', wishlist: 'విష్‌లిస్ట్', cart: 'కార్ట్', notifications: 'నోటిఫికేషన్‌లు', language: 'భాష' },
  kn: { account: 'ಖಾತೆ', wishlist: 'ವಿಶ್‌ಲಿಸ್ಟ್', cart: 'ಕಾರ್ಟ್', notifications: 'ಅಧಿಸೂಚನೆಗಳು', language: 'ಭಾಷೆ' },
};

const notifications = {
  en: { title: 'Notifications', empty: 'No notifications yet - order updates will show up here.', markAllRead: 'Mark all as read' },
  ta: { title: 'அறிவிப்புகள்', empty: 'இதுவரை அறிவிப்புகள் இல்லை - ஆர்டர் புதுப்பிப்புகள் இங்கே காண்பிக்கப்படும்.', markAllRead: 'அனைத்தையும் படித்ததாக குறிக்கவும்' },
  hi: { title: 'सूचनाएं', empty: 'अभी तक कोई सूचना नहीं - ऑर्डर अपडेट यहां दिखेंगे।', markAllRead: 'सभी को पढ़ा हुआ चिह्नित करें' },
  ml: { title: 'അറിയിപ്പുകൾ', empty: 'ഇതുവരെ അറിയിപ്പുകൾ ഇല്ല - ഓർഡർ അപ്‌ഡേറ്റുകൾ ഇവിടെ കാണിക്കും.', markAllRead: 'എല്ലാം വായിച്ചതായി അടയാളപ്പെടുത്തുക' },
  te: { title: 'నోటిఫికేషన్‌లు', empty: 'ఇంకా నోటిఫికేషన్‌లు లేవు - ఆర్డర్ అప్‌డేట్‌లు ఇక్కడ కనిపిస్తాయి.', markAllRead: 'అన్నింటినీ చదివినట్లు గుర్తించండి' },
  kn: { title: 'ಅಧಿಸೂಚನೆಗಳು', empty: 'ಇನ್ನೂ ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ - ಆರ್ಡರ್ ಅಪ್‌ಡೇಟ್‌ಗಳು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತವೆ.', markAllRead: 'ಎಲ್ಲವನ್ನೂ ಓದಿದಂತೆ ಗುರುತಿಸಿ' },
};

const footer = {
  en: { tagline: 'GROW BETTER • LIVE GREENER', description: 'A modern AgriTech nursery bringing plants, seeds, planters and gardening essentials together in one place.', shop: 'Shop', discover: 'Discover', account: 'Account', rights: 'All rights reserved.', builtFor: 'Built for a greener everyday.' },
  ta: { tagline: 'சிறப்பாக வளருங்கள் • பசுமையாக வாழுங்கள்', description: 'செடிகள், விதைகள், தொட்டிகள் மற்றும் தோட்ட தேவைகள் அனைத்தையும் ஒரே இடத்தில் வழங்கும் நவீன அக்ரிடெக் நர்சரி.', shop: 'கடை', discover: 'கண்டறியுங்கள்', account: 'கணக்கு', rights: 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.', builtFor: 'பசுமையான நாளைக்காக உருவாக்கப்பட்டது.' },
  hi: { tagline: 'बेहतर उगाएं • हरा जिएं', description: 'पौधे, बीज, गमले और बागवानी की हर ज़रूरत एक ही जगह लाने वाली एक आधुनिक एग्रीटेक नर्सरी।', shop: 'दुकान', discover: 'खोजें', account: 'खाता', rights: 'सर्वाधिकार सुरक्षित।', builtFor: 'एक हरे-भरे कल के लिए बनाया गया।' },
  ml: { tagline: 'നന്നായി വളരൂ • പച്ചയായി ജീവിക്കൂ', description: 'ചെടികൾ, വിത്തുകൾ, ചട്ടികൾ, തോട്ട ആവശ്യങ്ങൾ എല്ലാം ഒരിടത്ത് എത്തിക്കുന്ന ആധുനിക അഗ്രിടെക് നഴ്സറി.', shop: 'ഷോപ്പ്', discover: 'കണ്ടെത്തുക', account: 'അക്കൗണ്ട്', rights: 'എല്ലാ അവകാശങ്ങളും നിക്ഷിപ്തം.', builtFor: 'പച്ചപ്പുള്ള നാളെക്കായി നിർമ്മിച്ചത്.' },
  te: { tagline: 'బాగా పెంచండి • పచ్చగా జీవించండి', description: 'మొక్కలు, విత్తనాలు, కుండలు మరియు తోట అవసరాలను ఒకే చోట తీసుకువచ్చే ఆధునిక అగ్రిటెక్ నర్సరీ.', shop: 'షాప్', discover: 'కనుగొనండి', account: 'ఖాతా', rights: 'అన్ని హక్కులు రక్షించబడ్డాయి.', builtFor: 'పచ్చని రేపటి కోసం నిర్మించబడింది.' },
  kn: { tagline: 'ಚೆನ್ನಾಗಿ ಬೆಳೆಸಿ • ಹಸಿರಾಗಿ ಬದುಕಿ', description: 'ಸಸ್ಯಗಳು, ಬೀಜಗಳು, ಪಾಟ್‌ಗಳು ಮತ್ತು ತೋಟದ ಅಗತ್ಯಗಳನ್ನು ಒಂದೇ ಸ್ಥಳದಲ್ಲಿ ತರುವ ಆಧುನಿಕ ಅಗ್ರಿಟೆಕ್ ನರ್ಸರಿ.', shop: 'ಅಂಗಡಿ', discover: 'ಅನ್ವೇಷಿಸಿ', account: 'ಖಾತೆ', rights: 'ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.', builtFor: 'ಹಸಿರಾದ ನಾಳೆಗಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ.' },
};

const cart = {
  en: { title: 'Shopping cart', empty: 'Your cart is waiting for something green.', continueShopping: 'Continue shopping', orderSummary: 'Order summary', subtotal: 'Subtotal', delivery: 'Delivery', calculatedAtCheckout: 'Calculated at checkout', proceedToCheckout: 'Proceed to checkout', remove: 'Remove', quantity: 'Quantity', discount: 'Discount', total: 'Total', applyCoupon: 'Apply coupon' },
  ta: { title: 'கார்ட்', empty: 'உங்கள் கார்ட் ஏதோ பசுமையானதற்காக காத்திருக்கிறது.', continueShopping: 'தொடர்ந்து ஷாப்பிங் செய்யுங்கள்', orderSummary: 'ஆர்டர் சுருக்கம்', subtotal: 'மொத்தம்', delivery: 'டெலிவரி', calculatedAtCheckout: 'செக்அவுட்டில் கணக்கிடப்படும்', proceedToCheckout: 'செக்அவுட் செய்யவும்', remove: 'நீக்கு', quantity: 'எண்ணிக்கை', discount: 'தள்ளுபடி', total: 'மொத்த தொகை', applyCoupon: 'கூப்பன் பயன்படுத்து' },
  hi: { title: 'शॉपिंग कार्ट', empty: 'आपका कार्ट किसी हरे-भरे चीज़ का इंतज़ार कर रहा है।', continueShopping: 'खरीदारी जारी रखें', orderSummary: 'ऑर्डर सारांश', subtotal: 'उप-योग', delivery: 'डिलीवरी', calculatedAtCheckout: 'चेकआउट पर गणना की जाएगी', proceedToCheckout: 'चेकआउट पर जाएं', remove: 'हटाएं', quantity: 'मात्रा', discount: 'छूट', total: 'कुल', applyCoupon: 'कूपन लगाएं' },
  ml: { title: 'ഷോപ്പിംഗ് കാർട്ട്', empty: 'നിങ്ങളുടെ കാർട്ട് പച്ചയായ എന്തിനോ കാത്തിരിക്കുന്നു.', continueShopping: 'ഷോപ്പിംഗ് തുടരുക', orderSummary: 'ഓർഡർ സംഗ്രഹം', subtotal: 'ഉപആകെത്തുക', delivery: 'ഡെലിവറി', calculatedAtCheckout: 'ചെക്ക്ഔട്ടിൽ കണക്കാക്കും', proceedToCheckout: 'ചെക്ക്ഔട്ട് ചെയ്യുക', remove: 'നീക്കം ചെയ്യുക', quantity: 'അളവ്', discount: 'കിഴിവ്', total: 'ആകെ', applyCoupon: 'കൂപ്പൺ പ്രയോഗിക്കുക' },
  te: { title: 'షాపింగ్ కార్ట్', empty: 'మీ కార్ట్ పచ్చని దాని కోసం ఎదురుచూస్తోంది.', continueShopping: 'షాపింగ్ కొనసాగించండి', orderSummary: 'ఆర్డర్ సారాంశం', subtotal: 'ఉప మొత్తం', delivery: 'డెలివరీ', calculatedAtCheckout: 'చెక్అవుట్‌లో లెక్కించబడుతుంది', proceedToCheckout: 'చెక్అవుట్‌కు వెళ్లండి', remove: 'తొలగించు', quantity: 'పరిమాణం', discount: 'తగ్గింపు', total: 'మొత్తం', applyCoupon: 'కూపన్ వర్తింపజేయండి' },
  kn: { title: 'ಶಾಪಿಂಗ್ ಕಾರ್ಟ್', empty: 'ನಿಮ್ಮ ಕಾರ್ಟ್ ಹಸಿರಾದ ಏನೋ ಒಂದಕ್ಕಾಗಿ ಕಾಯುತ್ತಿದೆ.', continueShopping: 'ಶಾಪಿಂಗ್ ಮುಂದುವರಿಸಿ', orderSummary: 'ಆರ್ಡರ್ ಸಾರಾಂಶ', subtotal: 'ಉಪ ಮೊತ್ತ', delivery: 'ಡೆಲಿವರಿ', calculatedAtCheckout: 'ಚೆಕ್‌ಔಟ್‌ನಲ್ಲಿ ಲೆಕ್ಕಹಾಕಲಾಗುತ್ತದೆ', proceedToCheckout: 'ಚೆಕ್‌ಔಟ್‌ಗೆ ಮುಂದುವರಿಯಿರಿ', remove: 'ತೆಗೆದುಹಾಕಿ', quantity: 'ಪ್ರಮಾಣ', discount: 'ರಿಯಾಯಿತಿ', total: 'ಒಟ್ಟು', applyCoupon: 'ಕೂಪನ್ ಅನ್ವಯಿಸಿ' },
};

const auth = {
  en: { signIn: 'Sign in', createAccount: 'Create account', email: 'Email', password: 'Password', name: 'Name', logIn: 'Log in', logOut: 'Log out', phone: 'Phone number', emailRequired: 'Please enter your email address.', passwordRequired: 'Please enter your password.', invalidCredentials: 'Incorrect email or password.', heroLine1: 'Future of', heroLine2: 'Farming', heroLine3: 'Starts Here', heroDesc: 'Experience innovation through smart monitoring, intelligent alerts, and advanced agricultural systems.', createYourAccount: 'Create your account', fullName: 'Full Name', emailAddress: 'Email Address', hide: 'HIDE', show: 'SHOW', rememberMe: 'Remember Me', creatingAccount: 'CREATING ACCOUNT…', signingIn: 'SIGNING IN…', createAccountBtn: 'CREATE ACCOUNT', signInNow: 'SIGN IN NOW', notMemberYet: 'Not a member yet?', joinNow: 'Join Now!', alreadyHaveAccount: 'Already have an account?', close: 'Close and return to homepage', errInvalidEmail: "That email address doesn't look right.", errAccountExists: 'An account already exists with this email - try signing in instead.', errWeakPassword: 'Password should be at least 6 characters.', errGeneric: 'Something went wrong. Please try again.' },
  ta: { signIn: 'உள்நுழையவும்', createAccount: 'கணக்கை உருவாக்கவும்', email: 'மின்னஞ்சல்', password: 'கடவுச்சொல்', name: 'பெயர்', logIn: 'உள்நுழையவும்', logOut: 'வெளியேறு', phone: 'தொலைபேசி எண்', emailRequired: 'உங்கள் மின்னஞ்சல் முகவரியை உள்ளிடவும்.', passwordRequired: 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்.', invalidCredentials: 'தவறான மின்னஞ்சல் அல்லது கடவுச்சொல்.', heroLine1: 'விவசாயத்தின்', heroLine2: 'எதிர்காலம்', heroLine3: 'இங்கே தொடங்குகிறது', heroDesc: 'ஸ்மார்ட் மானிட்டரிங், அறிவார்ந்த எச்சரிக்கைகள் மற்றும் மேம்பட்ட விவசாய அமைப்புகள் மூலம் புத்தாக்கத்தை அனுபவிக்கவும்.', createYourAccount: 'உங்கள் கணக்கை உருவாக்கவும்', fullName: 'முழு பெயர்', emailAddress: 'மின்னஞ்சல் முகவரி', hide: 'மறை', show: 'காட்டு', rememberMe: 'என்னை நினைவில் வை', creatingAccount: 'கணக்கு உருவாக்கப்படுகிறது…', signingIn: 'உள்நுழைகிறது…', createAccountBtn: 'கணக்கை உருவாக்கவும்', signInNow: 'இப்போது உள்நுழையவும்', notMemberYet: 'இன்னும் உறுப்பினர் இல்லையா?', joinNow: 'இப்போது சேரவும்!', alreadyHaveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?', close: 'மூடி முகப்புக்குத் திரும்பு', errInvalidEmail: 'அந்த மின்னஞ்சல் முகவரி சரியாகத் தெரியவில்லை.', errAccountExists: 'இந்த மின்னஞ்சலில் ஏற்கனவே ஒரு கணக்கு உள்ளது - உள்நுழைய முயற்சிக்கவும்.', errWeakPassword: 'கடவுச்சொல் குறைந்தது 6 எழுத்துக்கள் இருக்க வேண்டும்.', errGeneric: 'ஏதோ தவறு நடந்தது. மீண்டும் முயற்சிக்கவும்.' },
  hi: { signIn: 'साइन इन करें', createAccount: 'खाता बनाएं', email: 'ईमेल', password: 'पासवर्ड', name: 'नाम', logIn: 'लॉग इन करें', logOut: 'लॉग आउट', phone: 'फ़ोन नंबर', emailRequired: 'कृपया अपना ईमेल पता दर्ज करें।', passwordRequired: 'कृपया अपना पासवर्ड दर्ज करें।', invalidCredentials: 'गलत ईमेल या पासवर्ड।', heroLine1: 'खेती का', heroLine2: 'भविष्य', heroLine3: 'यहीं से शुरू होता है', heroDesc: 'स्मार्ट मॉनिटरिंग, बुद्धिमान अलर्ट और उन्नत कृषि प्रणालियों के माध्यम से नवाचार का अनुभव करें।', createYourAccount: 'अपना खाता बनाएं', fullName: 'पूरा नाम', emailAddress: 'ईमेल पता', hide: 'छुपाएं', show: 'दिखाएं', rememberMe: 'मुझे याद रखें', creatingAccount: 'खाता बनाया जा रहा है…', signingIn: 'साइन इन हो रहा है…', createAccountBtn: 'खाता बनाएं', signInNow: 'अभी साइन इन करें', notMemberYet: 'अभी सदस्य नहीं हैं?', joinNow: 'अभी जुड़ें!', alreadyHaveAccount: 'पहले से खाता है?', close: 'बंद करें और होम पेज पर लौटें', errInvalidEmail: 'वह ईमेल पता सही नहीं लगता।', errAccountExists: 'इस ईमेल से पहले से एक खाता मौजूद है - इसके बजाय साइन इन करें।', errWeakPassword: 'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।', errGeneric: 'कुछ गलत हो गया। कृपया पुनः प्रयास करें।' },
  ml: { signIn: 'സൈൻ ഇൻ ചെയ്യുക', createAccount: 'അക്കൗണ്ട് സൃഷ്ടിക്കുക', email: 'ഇമെയിൽ', password: 'പാസ്‌വേഡ്', name: 'പേര്', logIn: 'ലോഗിൻ ചെയ്യുക', logOut: 'ലോഗ് ഔട്ട്', phone: 'ഫോൺ നമ്പർ', emailRequired: 'നിങ്ങളുടെ ഇമെയിൽ വിലാസം നൽകുക.', passwordRequired: 'നിങ്ങളുടെ പാസ്‌വേഡ് നൽകുക.', invalidCredentials: 'തെറ്റായ ഇമെയിൽ അല്ലെങ്കിൽ പാസ്‌വേഡ്.', heroLine1: 'കൃഷിയുടെ', heroLine2: 'ഭാവി', heroLine3: 'ഇവിടെ തുടങ്ങുന്നു', heroDesc: 'സ്മാർട്ട് മോണിറ്ററിംഗ്, ബുദ്ധിപരമായ അലേർട്ടുകൾ, വിപുലമായ കാർഷിക സംവിധാനങ്ങൾ എന്നിവയിലൂടെ നൂതനത്വം അനുഭവിക്കൂ.', createYourAccount: 'നിങ്ങളുടെ അക്കൗണ്ട് സൃഷ്ടിക്കുക', fullName: 'പൂർണ്ണ നാമം', emailAddress: 'ഇമെയിൽ വിലാസം', hide: 'മറയ്ക്കുക', show: 'കാണിക്കുക', rememberMe: 'എന്നെ ഓർമ്മിക്കുക', creatingAccount: 'അക്കൗണ്ട് സൃഷ്ടിക്കുന്നു…', signingIn: 'സൈൻ ഇൻ ചെയ്യുന്നു…', createAccountBtn: 'അക്കൗണ്ട് സൃഷ്ടിക്കുക', signInNow: 'ഇപ്പോൾ സൈൻ ഇൻ ചെയ്യുക', notMemberYet: 'ഇതുവരെ അംഗമല്ലേ?', joinNow: 'ഇപ്പോൾ ചേരുക!', alreadyHaveAccount: 'ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?', close: 'അടച്ച് ഹോമിലേക്ക് മടങ്ങുക', errInvalidEmail: 'ആ ഇമെയിൽ വിലാസം ശരിയായി തോന്നുന്നില്ല.', errAccountExists: 'ഈ ഇമെയിലിൽ ഒരു അക്കൗണ്ട് ഇതിനകം നിലവിലുണ്ട് - പകരം സൈൻ ഇൻ ചെയ്യാൻ ശ്രമിക്കുക.', errWeakPassword: 'പാസ്‌വേഡ് കുറഞ്ഞത് 6 പ്രതീകങ്ങൾ ആയിരിക്കണം.', errGeneric: 'എന്തോ പിശക് സംഭവിച്ചു. വീണ്ടും ശ്രമിക്കുക.' },
  te: { signIn: 'సైన్ ఇన్ చేయండి', createAccount: 'ఖాతా సృష్టించండి', email: 'ఇమెయిల్', password: 'పాస్‌వర్డ్', name: 'పేరు', logIn: 'లాగిన్ చేయండి', logOut: 'లాగ్ అవుట్', phone: 'ఫోన్ నంబర్', emailRequired: 'దయచేసి మీ ఇమెయిల్ చిరునామాను నమోదు చేయండి.', passwordRequired: 'దయచేసి మీ పాస్‌వర్డ్‌ను నమోదు చేయండి.', invalidCredentials: 'తప్పు ఇమెయిల్ లేదా పాస్‌వర్డ్.', heroLine1: 'వ్యవసాయ', heroLine2: 'భవిష్యత్తు', heroLine3: 'ఇక్కడ ప్రారంభమవుతుంది', heroDesc: 'స్మార్ట్ మానిటరింగ్, తెలివైన హెచ్చరికలు మరియు అధునాతన వ్యవసాయ వ్యవస్థల ద్వారా ఆవిష్కరణను అనుభవించండి.', createYourAccount: 'మీ ఖాతాను సృష్టించండి', fullName: 'పూర్తి పేరు', emailAddress: 'ఇమెయిల్ చిరునామా', hide: 'దాచు', show: 'చూపించు', rememberMe: 'నన్ను గుర్తుంచుకో', creatingAccount: 'ఖాతా సృష్టించబడుతోంది…', signingIn: 'సైన్ ఇన్ అవుతోంది…', createAccountBtn: 'ఖాతా సృష్టించండి', signInNow: 'ఇప్పుడే సైన్ ఇన్ చేయండి', notMemberYet: 'ఇంకా సభ్యులు కాదా?', joinNow: 'ఇప్పుడే చేరండి!', alreadyHaveAccount: 'ఇప్పటికే ఖాతా ఉందా?', close: 'మూసివేసి హోమ్‌కు తిరిగి వెళ్లండి', errInvalidEmail: 'ఆ ఇమెయిల్ చిరునామా సరిగ్గా కనిపించడం లేదు.', errAccountExists: 'ఈ ఇమెయిల్‌తో ఖాతా ఇప్పటికే ఉంది - బదులుగా సైన్ ఇన్ చేయడానికి ప్రయత్నించండి.', errWeakPassword: 'పాస్‌వర్డ్ కనీసం 6 అక్షరాలు ఉండాలి.', errGeneric: 'ఏదో తప్పు జరిగింది. దయచేసి మళ్ళీ ప్రయత్నించండి.' },
  kn: { signIn: 'ಸೈನ್ ಇನ್ ಮಾಡಿ', createAccount: 'ಖಾತೆ ರಚಿಸಿ', email: 'ಇಮೇಲ್', password: 'ಪಾಸ್‌ವರ್ಡ್', name: 'ಹೆಸರು', logIn: 'ಲಾಗ್ ಇನ್ ಮಾಡಿ', logOut: 'ಲಾಗ್ ಔಟ್', phone: 'ಫೋನ್ ಸಂಖ್ಯೆ', emailRequired: 'ದಯವಿಟ್ಟು ನಿಮ್ಮ ಇಮೇಲ್ ವಿಳಾಸವನ್ನು ನಮೂದಿಸಿ.', passwordRequired: 'ದಯವಿಟ್ಟು ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ.', invalidCredentials: 'ತಪ್ಪಾದ ಇಮೇಲ್ ಅಥವಾ ಪಾಸ್‌ವರ್ಡ್.', heroLine1: 'ಕೃಷಿಯ', heroLine2: 'ಭವಿಷ್ಯ', heroLine3: 'ಇಲ್ಲಿ ಪ್ರಾರಂಭವಾಗುತ್ತದೆ', heroDesc: 'ಸ್ಮಾರ್ಟ್ ಮಾನಿಟರಿಂಗ್, ಬುದ್ಧಿವಂತ ಎಚ್ಚರಿಕೆಗಳು ಮತ್ತು ಸುಧಾರಿತ ಕೃಷಿ ವ್ಯವಸ್ಥೆಗಳ ಮೂಲಕ ನಾವೀನ್ಯತೆಯನ್ನು ಅನುಭವಿಸಿ.', createYourAccount: 'ನಿಮ್ಮ ಖಾತೆಯನ್ನು ರಚಿಸಿ', fullName: 'ಪೂರ್ಣ ಹೆಸರು', emailAddress: 'ಇಮೇಲ್ ವಿಳಾಸ', hide: 'ಮರೆಮಾಡಿ', show: 'ತೋರಿಸಿ', rememberMe: 'ನನ್ನನ್ನು ನೆನಪಿಡಿ', creatingAccount: 'ಖಾತೆ ರಚಿಸಲಾಗುತ್ತಿದೆ…', signingIn: 'ಸೈನ್ ಇನ್ ಆಗುತ್ತಿದೆ…', createAccountBtn: 'ಖಾತೆ ರಚಿಸಿ', signInNow: 'ಈಗ ಸೈನ್ ಇನ್ ಮಾಡಿ', notMemberYet: 'ಇನ್ನೂ ಸದಸ್ಯರಲ್ಲವೇ?', joinNow: 'ಈಗ ಸೇರಿ!', alreadyHaveAccount: 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?', close: 'ಮುಚ್ಚಿ ಹೋಮ್‌ಗೆ ಹಿಂತಿರುಗಿ', errInvalidEmail: 'ಆ ಇಮೇಲ್ ವಿಳಾಸ ಸರಿಯಾಗಿ ಕಾಣುತ್ತಿಲ್ಲ.', errAccountExists: 'ಈ ಇಮೇಲ್‌ನೊಂದಿಗೆ ಖಾತೆ ಈಗಾಗಲೇ ಅಸ್ತಿತ್ವದಲ್ಲಿದೆ - ಬದಲಿಗೆ ಸೈನ್ ಇನ್ ಮಾಡಲು ಪ್ರಯತ್ನಿಸಿ.', errWeakPassword: 'ಪಾಸ್‌ವರ್ಡ್ ಕನಿಷ್ಠ 6 ಅಕ್ಷರಗಳಿರಬೇಕು.', errGeneric: 'ಏನೋ ತಪ್ಪಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.' },
};

const checkout = {
  en: { customerInfo: 'Customer information', address: 'Address', deliveryAddress: 'Delivery address', paymentMethod: 'Payment method', orderSummary: 'Order summary', placeOrder: 'Place order', placingOrder: 'Placing order…', paymentSuccessful: 'Payment successful', paymentFailed: 'Payment failed', addAddress: 'Add address', title: 'Checkout', secureCheckout: 'Secure checkout', emptyCart: "Your cart is empty - add something before checking out.", step1: 'Delivery address', step2: 'Payment method', step3: 'Review your order', loadingAddresses: 'Loading addresses…', addNewAddress: '+ Add a new address', useSavedAddress: '← Use a saved address', cashOnDelivery: 'Cash on Delivery', upi: 'UPI', delivery: 'Delivery', free: 'Free', total: 'Total', secureNote: '🔒 Your information is encrypted and secure.', fillRequiredFields: 'Please fill in all the required address fields.', selectOrAddAddress: 'Please select or add a delivery address.', couldNotPlaceOrder: 'Could not place your order. Please try again.', orderPlacedToast: 'Order placed! Thank you for shopping with us.', viewOrders: 'View Orders' },
  ta: { customerInfo: 'வாடிக்கையாளர் தகவல்', address: 'முகவரி', deliveryAddress: 'டெலிவரி முகவரி', paymentMethod: 'கட்டண முறை', orderSummary: 'ஆர்டர் சுருக்கம்', placeOrder: 'ஆர்டர் செய்யவும்', placingOrder: 'ஆர்டர் செய்யப்படுகிறது…', paymentSuccessful: 'கட்டணம் வெற்றிகரமாக முடிந்தது', paymentFailed: 'கட்டணம் தோல்வியடைந்தது', addAddress: 'முகவரி சேர்', title: 'செக்அவுட்', secureCheckout: 'பாதுகாப்பான செக்அவுட்', emptyCart: 'உங்கள் கார்ட் காலியாக உள்ளது - செக்அவுட் செய்வதற்கு முன் ஏதாவது சேர்க்கவும்.', step1: 'டெலிவரி முகவரி', step2: 'கட்டண முறை', step3: 'உங்கள் ஆர்டரை மதிப்பாய்வு செய்யவும்', loadingAddresses: 'முகவரிகள் ஏற்றப்படுகின்றன…', addNewAddress: '+ புதிய முகவரியைச் சேர்க்கவும்', useSavedAddress: '← சேமிக்கப்பட்ட முகவரியைப் பயன்படுத்தவும்', cashOnDelivery: 'டெலிவரியில் பணம் செலுத்துதல்', upi: 'UPI', delivery: 'டெலிவரி', free: 'இலவசம்', total: 'மொத்த தொகை', secureNote: '🔒 உங்கள் தகவல் குறியாக்கம் செய்யப்பட்டு பாதுகாப்பாக உள்ளது.', fillRequiredFields: 'தேவையான அனைத்து முகவரி விவரங்களையும் நிரப்பவும்.', selectOrAddAddress: 'டெலிவரி முகவரியைத் தேர்ந்தெடுக்கவும் அல்லது சேர்க்கவும்.', couldNotPlaceOrder: 'உங்கள் ஆர்டரை செய்ய முடியவில்லை. மீண்டும் முயற்சிக்கவும்.', orderPlacedToast: 'ஆர்டர் செய்யப்பட்டது! எங்களிடம் ஷாப்பிங் செய்ததற்கு நன்றி.', viewOrders: 'ஆர்டர்களைக் காண்க' },
  hi: { customerInfo: 'ग्राहक जानकारी', address: 'पता', deliveryAddress: 'डिलीवरी पता', paymentMethod: 'भुगतान विधि', orderSummary: 'ऑर्डर सारांश', placeOrder: 'ऑर्डर करें', placingOrder: 'ऑर्डर किया जा रहा है…', paymentSuccessful: 'भुगतान सफल', paymentFailed: 'भुगतान असफल', addAddress: 'पता जोड़ें', title: 'चेकआउट', secureCheckout: 'सुरक्षित चेकआउट', emptyCart: 'आपका कार्ट खाली है - चेकआउट करने से पहले कुछ जोड़ें।', step1: 'डिलीवरी पता', step2: 'भुगतान विधि', step3: 'अपने ऑर्डर की समीक्षा करें', loadingAddresses: 'पते लोड हो रहे हैं…', addNewAddress: '+ नया पता जोड़ें', useSavedAddress: '← सहेजा गया पता उपयोग करें', cashOnDelivery: 'कैश ऑन डिलीवरी', upi: 'UPI', delivery: 'डिलीवरी', free: 'मुफ़्त', total: 'कुल', secureNote: '🔒 आपकी जानकारी एन्क्रिप्टेड और सुरक्षित है।', fillRequiredFields: 'कृपया सभी आवश्यक पता फ़ील्ड भरें।', selectOrAddAddress: 'कृपया डिलीवरी पता चुनें या जोड़ें।', couldNotPlaceOrder: 'आपका ऑर्डर नहीं दिया जा सका। कृपया पुनः प्रयास करें।', orderPlacedToast: 'ऑर्डर दे दिया गया! हमारे साथ खरीदारी करने के लिए धन्यवाद।', viewOrders: 'ऑर्डर देखें' },
  ml: { customerInfo: 'ഉപഭോക്തൃ വിവരങ്ങൾ', address: 'വിലാസം', deliveryAddress: 'ഡെലിവറി വിലാസം', paymentMethod: 'പേയ്‌മെന്റ് രീതി', orderSummary: 'ഓർഡർ സംഗ്രഹം', placeOrder: 'ഓർഡർ ചെയ്യുക', placingOrder: 'ഓർഡർ ചെയ്യുന്നു…', paymentSuccessful: 'പേയ്‌മെന്റ് വിജയകരം', paymentFailed: 'പേയ്‌മെന്റ് പരാജയപ്പെട്ടു', addAddress: 'വിലാസം ചേർക്കുക', title: 'ചെക്ക്ഔട്ട്', secureCheckout: 'സുരക്ഷിത ചെക്ക്ഔട്ട്', emptyCart: 'നിങ്ങളുടെ കാർട്ട് ശൂന്യമാണ് - ചെക്ക്ഔട്ട് ചെയ്യുന്നതിന് മുമ്പ് എന്തെങ്കിലും ചേർക്കുക.', step1: 'ഡെലിവറി വിലാസം', step2: 'പേയ്‌മെന്റ് രീതി', step3: 'നിങ്ങളുടെ ഓർഡർ അവലോകനം ചെയ്യുക', loadingAddresses: 'വിലാസങ്ങൾ ലോഡ് ചെയ്യുന്നു…', addNewAddress: '+ പുതിയ വിലാസം ചേർക്കുക', useSavedAddress: '← സേവ് ചെയ്ത വിലാസം ഉപയോഗിക്കുക', cashOnDelivery: 'ഡെലിവറിയിൽ പണം നൽകുക', upi: 'UPI', delivery: 'ഡെലിവറി', free: 'സൗജന്യം', total: 'ആകെ', secureNote: '🔒 നിങ്ങളുടെ വിവരങ്ങൾ എൻക്രിപ്റ്റ് ചെയ്ത് സുരക്ഷിതമാണ്.', fillRequiredFields: 'ദയവായി എല്ലാ ആവശ്യമായ വിലാസ ഫീൽഡുകളും പൂരിപ്പിക്കുക.', selectOrAddAddress: 'ദയവായി ഡെലിവറി വിലാസം തിരഞ്ഞെടുക്കുക അല്ലെങ്കിൽ ചേർക്കുക.', couldNotPlaceOrder: 'നിങ്ങളുടെ ഓർഡർ നൽകാൻ കഴിഞ്ഞില്ല. വീണ്ടും ശ്രമിക്കുക.', orderPlacedToast: 'ഓർഡർ ചെയ്തു! ഞങ്ങളിൽ നിന്ന് ഷോപ്പിംഗ് ചെയ്തതിന് നന്ദി.', viewOrders: 'ഓർഡറുകൾ കാണുക' },
  te: { customerInfo: 'కస్టమర్ సమాచారం', address: 'చిరునామా', deliveryAddress: 'డెలివరీ చిరునామా', paymentMethod: 'చెల్లింపు విధానం', orderSummary: 'ఆర్డర్ సారాంశం', placeOrder: 'ఆర్డర్ చేయండి', placingOrder: 'ఆర్డర్ చేయబడుతోంది…', paymentSuccessful: 'చెల్లింపు విజయవంతమైంది', paymentFailed: 'చెల్లింపు విఫలమైంది', addAddress: 'చిరునామా జోడించండి', title: 'చెక్అవుట్', secureCheckout: 'సురక్షిత చెక్అవుట్', emptyCart: 'మీ కార్ట్ ఖాళీగా ఉంది - చెక్అవుట్ చేయడానికి ముందు ఏదైనా జోడించండి.', step1: 'డెలివరీ చిరునామా', step2: 'చెల్లింపు విధానం', step3: 'మీ ఆర్డర్‌ను సమీక్షించండి', loadingAddresses: 'చిరునామాలు లోడ్ అవుతున్నాయి…', addNewAddress: '+ కొత్త చిరునామా జోడించండి', useSavedAddress: '← సేవ్ చేసిన చిరునామాను ఉపయోగించండి', cashOnDelivery: 'డెలివరీ సమయంలో నగదు చెల్లింపు', upi: 'UPI', delivery: 'డెలివరీ', free: 'ఉచితం', total: 'మొత్తం', secureNote: '🔒 మీ సమాచారం గుప్తీకరించబడింది మరియు సురక్షితంగా ఉంది.', fillRequiredFields: 'దయచేసి అవసరమైన అన్ని చిరునామా ఫీల్డ్‌లను పూరించండి.', selectOrAddAddress: 'దయచేసి డెలివరీ చిరునామాను ఎంచుకోండి లేదా జోడించండి.', couldNotPlaceOrder: 'మీ ఆర్డర్‌ను ఉంచడం సాధ్యం కాలేదు. దయచేసి మళ్ళీ ప్రయత్నించండి.', orderPlacedToast: 'ఆర్డర్ చేయబడింది! మాతో షాపింగ్ చేసినందుకు ధన్యవాదాలు.', viewOrders: 'ఆర్డర్‌లను చూడండి' },
  kn: { customerInfo: 'ಗ್ರಾಹಕ ಮಾಹಿತಿ', address: 'ವಿಳಾಸ', deliveryAddress: 'ಡೆಲಿವರಿ ವಿಳಾಸ', paymentMethod: 'ಪಾವತಿ ವಿಧಾನ', orderSummary: 'ಆರ್ಡರ್ ಸಾರಾಂಶ', placeOrder: 'ಆರ್ಡರ್ ಮಾಡಿ', placingOrder: 'ಆರ್ಡರ್ ಮಾಡಲಾಗುತ್ತಿದೆ…', paymentSuccessful: 'ಪಾವತಿ ಯಶಸ್ವಿಯಾಗಿದೆ', paymentFailed: 'ಪಾವತಿ ವಿಫಲವಾಗಿದೆ', addAddress: 'ವಿಳಾಸ ಸೇರಿಸಿ', title: 'ಚೆಕ್‌ಔಟ್', secureCheckout: 'ಸುರಕ್ಷಿತ ಚೆಕ್‌ಔಟ್', emptyCart: 'ನಿಮ್ಮ ಕಾರ್ಟ್ ಖಾಲಿಯಾಗಿದೆ - ಚೆಕ್‌ಔಟ್ ಮಾಡುವ ಮೊದಲು ಏನನ್ನಾದರೂ ಸೇರಿಸಿ.', step1: 'ಡೆಲಿವರಿ ವಿಳಾಸ', step2: 'ಪಾವತಿ ವಿಧಾನ', step3: 'ನಿಮ್ಮ ಆರ್ಡರ್ ಅನ್ನು ಪರಿಶೀಲಿಸಿ', loadingAddresses: 'ವಿಳಾಸಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ…', addNewAddress: '+ ಹೊಸ ವಿಳಾಸ ಸೇರಿಸಿ', useSavedAddress: '← ಉಳಿಸಿದ ವಿಳಾಸ ಬಳಸಿ', cashOnDelivery: 'ಡೆಲಿವರಿಯಲ್ಲಿ ನಗದು ಪಾವತಿ', upi: 'UPI', delivery: 'ಡೆಲಿವರಿ', free: 'ಉಚಿತ', total: 'ಒಟ್ಟು', secureNote: '🔒 ನಿಮ್ಮ ಮಾಹಿತಿ ಎನ್‌ಕ್ರಿಪ್ಟ್ ಮಾಡಲ್ಪಟ್ಟಿದೆ ಮತ್ತು ಸುರಕ್ಷಿತವಾಗಿದೆ.', fillRequiredFields: 'ದಯವಿಟ್ಟು ಎಲ್ಲಾ ಅಗತ್ಯ ವಿಳಾಸ ಕ್ಷೇತ್ರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ.', selectOrAddAddress: 'ದಯವಿಟ್ಟು ಡೆಲಿವರಿ ವಿಳಾಸವನ್ನು ಆಯ್ಕೆಮಾಡಿ ಅಥವಾ ಸೇರಿಸಿ.', couldNotPlaceOrder: 'ನಿಮ್ಮ ಆರ್ಡರ್ ಅನ್ನು ಇರಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.', orderPlacedToast: 'ಆರ್ಡರ್ ಮಾಡಲಾಗಿದೆ! ನಮ್ಮೊಂದಿಗೆ ಶಾಪಿಂಗ್ ಮಾಡಿದ್ದಕ್ಕಾಗಿ ಧನ್ಯವಾದಗಳು.', viewOrders: 'ಆರ್ಡರ್‌ಗಳನ್ನು ವೀಕ್ಷಿಸಿ' },
};

const product = {
  en: { home: 'Home', notFound: 'Product not found', backToHome: 'Back to home', size: 'Size', light: 'Light', idealLocation: 'Ideal location', maintenance: 'Maintenance', watering: 'Watering', saved: 'Saved', saveForLater: 'Save for later', youMayAlsoLike: 'You may also like', descTemplate: '{name} is grown at our Muttukadu lab under monitored conditions and passes our 99.2% health check before it ships. Pairs well with our terracotta pots and organic potting mix for the best start.' },
  ta: { home: 'முகப்பு', notFound: 'தயாரிப்பு கிடைக்கவில்லை', backToHome: 'முகப்புக்குத் திரும்பு', size: 'அளவு', light: 'ஒளி', idealLocation: 'ஏற்ற இடம்', maintenance: 'பராமரிப்பு', watering: 'நீர்ப்பாசனம்', saved: 'சேமிக்கப்பட்டது', saveForLater: 'பின்னர் சேமி', youMayAlsoLike: 'இதுவும் உங்களுக்குப் பிடிக்கலாம்', descTemplate: '{name} எங்கள் முத்துக்காடு ஆய்வகத்தில் கண்காணிக்கப்பட்ட நிலைமைகளின் கீழ் வளர்க்கப்பட்டு, அனுப்பும் முன் எங்கள் 99.2% ஆரோக்கிய சோதனையில் தேர்ச்சி பெறுகிறது. எங்கள் டெரகோட்டா தொட்டிகள் மற்றும் இயற்கை மண் கலவையுடன் சிறப்பாகப் பொருந்தும்.' },
  hi: { home: 'होम', notFound: 'उत्पाद नहीं मिला', backToHome: 'होम पर वापस जाएं', size: 'आकार', light: 'रोशनी', idealLocation: 'उपयुक्त स्थान', maintenance: 'रखरखाव', watering: 'पानी देना', saved: 'सहेजा गया', saveForLater: 'बाद के लिए सहेजें', youMayAlsoLike: 'आपको यह भी पसंद आ सकता है', descTemplate: '{name} हमारी मुत्तुकाडु लैब में निगरानी की गई परिस्थितियों में उगाया जाता है और भेजे जाने से पहले हमारी 99.2% स्वास्थ्य जांच पास करता है। हमारे टेराकोटा गमलों और जैविक पॉटिंग मिश्रण के साथ बेहतरीन शुरुआत के लिए उपयुक्त।' },
  ml: { home: 'ഹോം', notFound: 'ഉൽപ്പന്നം കണ്ടെത്തിയില്ല', backToHome: 'ഹോമിലേക്ക് മടങ്ങുക', size: 'വലുപ്പം', light: 'വെളിച്ചം', idealLocation: 'അനുയോജ്യമായ സ്ഥലം', maintenance: 'പരിപാലനം', watering: 'നനയ്ക്കൽ', saved: 'സേവ് ചെയ്തു', saveForLater: 'പിന്നീട് സേവ് ചെയ്യുക', youMayAlsoLike: 'നിങ്ങൾക്ക് ഇതും ഇഷ്ടപ്പെട്ടേക്കാം', descTemplate: '{name} ഞങ്ങളുടെ മുട്ടുകാട് ലാബിൽ നിരീക്ഷിത സാഹചര്യങ്ങളിൽ വളർത്തി, അയക്കുന്നതിന് മുമ്പ് ഞങ്ങളുടെ 99.2% ആരോഗ്യ പരിശോധന വിജയിക്കുന്നു. ഞങ്ങളുടെ ടെറാക്കോട്ട ചട്ടികളും ജൈവ പോട്ടിംഗ് മിശ്രിതവുമായി നന്നായി യോജിക്കുന്നു.' },
  te: { home: 'హోమ్', notFound: 'ఉత్పత్తి కనుగొనబడలేదు', backToHome: 'హోమ్‌కు తిరిగి వెళ్లండి', size: 'పరిమాణం', light: 'వెలుతురు', idealLocation: 'అనువైన ప్రదేశం', maintenance: 'నిర్వహణ', watering: 'నీరు పెట్టడం', saved: 'సేవ్ చేయబడింది', saveForLater: 'తర్వాత కోసం సేవ్ చేయండి', youMayAlsoLike: 'మీకు ఇది కూడా నచ్చవచ్చు', descTemplate: '{name} మా ముత్తుకాడు ల్యాబ్‌లో పర్యవేక్షించబడిన పరిస్థితుల్లో పెంచబడి, పంపే ముందు మా 99.2% ఆరోగ్య తనిఖీలో ఉత్తీర్ణత సాధిస్తుంది. మా టెర్రకోట కుండలు మరియు సేంద్రీయ పాటింగ్ మిశ్రమంతో బాగా సరిపోతుంది.' },
  kn: { home: 'ಹೋಮ್', notFound: 'ಉತ್ಪನ್ನ ಕಂಡುಬಂದಿಲ್ಲ', backToHome: 'ಹೋಮ್‌ಗೆ ಹಿಂತಿರುಗಿ', size: 'ಗಾತ್ರ', light: 'ಬೆಳಕು', idealLocation: 'ಸೂಕ್ತ ಸ್ಥಳ', maintenance: 'ನಿರ್ವಹಣೆ', watering: 'ನೀರುಣಿಸುವಿಕೆ', saved: 'ಉಳಿಸಲಾಗಿದೆ', saveForLater: 'ನಂತರಕ್ಕಾಗಿ ಉಳಿಸಿ', youMayAlsoLike: 'ನೀವು ಇದನ್ನೂ ಇಷ್ಟಪಡಬಹುದು', descTemplate: '{name} ನಮ್ಮ ಮುತ್ತುಕಾಡು ಲ್ಯಾಬ್‌ನಲ್ಲಿ ಮೇಲ್ವಿಚಾರಣೆಯ ಪರಿಸ್ಥಿತಿಗಳಲ್ಲಿ ಬೆಳೆಸಲಾಗುತ್ತದೆ ಮತ್ತು ಕಳುಹಿಸುವ ಮೊದಲು ನಮ್ಮ 99.2% ಆರೋಗ್ಯ ತಪಾಸಣೆಯಲ್ಲಿ ಉತ್ತೀರ್ಣರಾಗುತ್ತದೆ. ನಮ್ಮ ಟೆರಾಕೋಟಾ ಪಾಟ್‌ಗಳು ಮತ್ತು ಸಾವಯವ ಪಾಟಿಂಗ್ ಮಿಶ್ರಣದೊಂದಿಗೆ ಚೆನ್ನಾಗಿ ಹೊಂದಿಕೊಳ್ಳುತ್ತದೆ.' },
};

const orders = {
  en: { myOrders: 'My orders', orderId: 'Order ID', orderDate: 'Order date', trackOrder: 'Track order', viewDetails: 'View details', statuses: { 'Order Placed': 'Order Placed', 'Order Confirmed': 'Order Confirmed', 'Order Processing': 'Order Processing', Packed: 'Packed', Shipped: 'Shipped', 'Out for Delivery': 'Out for Delivery', Delivered: 'Delivered', Cancelled: 'Cancelled' } },
  ta: { myOrders: 'எனது ஆர்டர்கள்', orderId: 'ஆர்டர் ஐடி', orderDate: 'ஆர்டர் தேதி', trackOrder: 'ஆர்டரை கண்காணிக்கவும்', viewDetails: 'விவரங்களைக் காண்க', statuses: { 'Order Placed': 'ஆர்டர் செய்யப்பட்டது', 'Order Confirmed': 'ஆர்டர் உறுதி செய்யப்பட்டது', 'Order Processing': 'ஆர்டர் தயாராகிறது', Packed: 'பேக் செய்யப்பட்டது', Shipped: 'அனுப்பப்பட்டது', 'Out for Delivery': 'டெலிவரிக்கு புறப்பட்டது', Delivered: 'டெலிவரி செய்யப்பட்டது', Cancelled: 'ரத்து செய்யப்பட்டது' } },
  hi: { myOrders: 'मेरे ऑर्डर', orderId: 'ऑर्डर आईडी', orderDate: 'ऑर्डर तिथि', trackOrder: 'ऑर्डर ट्रैक करें', viewDetails: 'विवरण देखें', statuses: { 'Order Placed': 'ऑर्डर दिया गया', 'Order Confirmed': 'ऑर्डर की पुष्टि हुई', 'Order Processing': 'ऑर्डर तैयार हो रहा है', Packed: 'पैक किया गया', Shipped: 'भेज दिया गया', 'Out for Delivery': 'डिलीवरी के लिए निकल गया', Delivered: 'डिलीवर हो गया', Cancelled: 'रद्द किया गया' } },
  ml: { myOrders: 'എന്റെ ഓർഡറുകൾ', orderId: 'ഓർഡർ ഐഡി', orderDate: 'ഓർഡർ തീയതി', trackOrder: 'ഓർഡർ ട്രാക്ക് ചെയ്യുക', viewDetails: 'വിശദാംശങ്ങൾ കാണുക', statuses: { 'Order Placed': 'ഓർഡർ ചെയ്തു', 'Order Confirmed': 'ഓർഡർ സ്ഥിരീകരിച്ചു', 'Order Processing': 'ഓർഡർ തയ്യാറാകുന്നു', Packed: 'പാക്ക് ചെയ്തു', Shipped: 'അയച്ചു', 'Out for Delivery': 'ഡെലിവറിക്ക് പുറപ്പെട്ടു', Delivered: 'ഡെലിവർ ചെയ്തു', Cancelled: 'റദ്ദാക്കി' } },
  te: { myOrders: 'నా ఆర్డర్‌లు', orderId: 'ఆర్డర్ ఐడి', orderDate: 'ఆర్డర్ తేదీ', trackOrder: 'ఆర్డర్‌ను ట్రాక్ చేయండి', viewDetails: 'వివరాలు చూడండి', statuses: { 'Order Placed': 'ఆర్డర్ చేయబడింది', 'Order Confirmed': 'ఆర్డర్ నిర్ధారించబడింది', 'Order Processing': 'ఆర్డర్ సిద్ధమవుతోంది', Packed: 'ప్యాక్ చేయబడింది', Shipped: 'పంపబడింది', 'Out for Delivery': 'డెలివరీకి బయలుదేరింది', Delivered: 'డెలివరీ చేయబడింది', Cancelled: 'రద్దు చేయబడింది' } },
  kn: { myOrders: 'ನನ್ನ ಆರ್ಡರ್‌ಗಳು', orderId: 'ಆರ್ಡರ್ ಐಡಿ', orderDate: 'ಆರ್ಡರ್ ದಿನಾಂಕ', trackOrder: 'ಆರ್ಡರ್ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ', viewDetails: 'ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ', statuses: { 'Order Placed': 'ಆರ್ಡರ್ ಮಾಡಲಾಗಿದೆ', 'Order Confirmed': 'ಆರ್ಡರ್ ದೃಢಪಡಿಸಲಾಗಿದೆ', 'Order Processing': 'ಆರ್ಡರ್ ಸಿದ್ಧವಾಗುತ್ತಿದೆ', Packed: 'ಪ್ಯಾಕ್ ಮಾಡಲಾಗಿದೆ', Shipped: 'ರವಾನಿಸಲಾಗಿದೆ', 'Out for Delivery': 'ಡೆಲಿವರಿಗೆ ಹೊರಟಿದೆ', Delivered: 'ಡೆಲಿವರಿ ಆಗಿದೆ', Cancelled: 'ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ' } },
};

const common = {
  en: { addToCart: 'Add to cart', buyNow: 'Buy now', viewDetails: 'Details', trackOrder: 'Track order', outOfStock: 'Out of stock', lowStock: 'Low stock', clearFilters: 'Clear filters', noProductsFound: 'No products found', tryDifferentSearch: 'Try a different word, or check the spelling.', loading: 'Loading...', submit: 'Submit', cancel: 'Cancel', save: 'Save', delete: 'Delete', edit: 'Edit', confirm: 'Confirm', close: 'Close', back: 'Back', next: 'Next', previous: 'Previous', continueLabel: 'Continue', retry: 'Retry', success: 'Success', error: 'Something went wrong. Please try again.' },
  ta: { addToCart: 'கார்ட்டில் சேர்', buyNow: 'இப்போது வாங்கு', viewDetails: 'விவரங்கள்', trackOrder: 'ஆர்டரை கண்காணிக்கவும்', outOfStock: 'கையிருப்பில் இல்லை', lowStock: 'கையிருப்பு குறைவு', clearFilters: 'வடிகட்டிகளை அழிக்கவும்', noProductsFound: 'தயாரிப்புகள் எதுவும் இல்லை', tryDifferentSearch: 'வேறு வார்த்தையை முயற்சிக்கவும், அல்லது எழுத்துப்பிழையை சரிபார்க்கவும்.', loading: 'ஏற்றுகிறது...', submit: 'சமர்ப்பிக்கவும்', cancel: 'ரத்து செய்', save: 'சேமி', delete: 'நீக்கு', edit: 'திருத்து', confirm: 'உறுதிப்படுத்து', close: 'மூடு', back: 'பின்செல்', next: 'அடுத்து', previous: 'முந்தைய', continueLabel: 'தொடரவும்', retry: 'மீண்டும் முயற்சி', success: 'வெற்றி', error: 'ஏதோ தவறு நடந்தது. மீண்டும் முயற்சிக்கவும்.' },
  hi: { addToCart: 'कार्ट में जोड़ें', buyNow: 'अभी खरीदें', viewDetails: 'विवरण', trackOrder: 'ऑर्डर ट्रैक करें', outOfStock: 'स्टॉक में नहीं', lowStock: 'सीमित स्टॉक', clearFilters: 'फ़िल्टर हटाएं', noProductsFound: 'कोई उत्पाद नहीं मिला', tryDifferentSearch: 'कोई अन्य शब्द आज़माएं, या वर्तनी जांचें।', loading: 'लोड हो रहा है...', submit: 'सबमिट करें', cancel: 'रद्द करें', save: 'सहेजें', delete: 'हटाएं', edit: 'संपादित करें', confirm: 'पुष्टि करें', close: 'बंद करें', back: 'वापस', next: 'अगला', previous: 'पिछला', continueLabel: 'जारी रखें', retry: 'पुनः प्रयास करें', success: 'सफल', error: 'कुछ गलत हो गया। कृपया पुनः प्रयास करें।' },
  ml: { addToCart: 'കാർട്ടിൽ ചേർക്കുക', buyNow: 'ഇപ്പോൾ വാങ്ങുക', viewDetails: 'വിശദാംശങ്ങൾ', trackOrder: 'ഓർഡർ ട്രാക്ക് ചെയ്യുക', outOfStock: 'സ്റ്റോക്ക് ഇല്ല', lowStock: 'സ്റ്റോക്ക് കുറവാണ്', clearFilters: 'ഫിൽട്ടറുകൾ മായ്ക്കുക', noProductsFound: 'ഉൽപ്പന്നങ്ങളൊന്നും കണ്ടെത്തിയില്ല', tryDifferentSearch: 'മറ്റൊരു വാക്ക് ശ്രമിക്കുക, അല്ലെങ്കിൽ സ്പെല്ലിംഗ് പരിശോധിക്കുക.', loading: 'ലോഡ് ചെയ്യുന്നു...', submit: 'സമർപ്പിക്കുക', cancel: 'റദ്ദാക്കുക', save: 'സേവ് ചെയ്യുക', delete: 'ഇല്ലാതാക്കുക', edit: 'എഡിറ്റ് ചെയ്യുക', confirm: 'സ്ഥിരീകരിക്കുക', close: 'അടയ്ക്കുക', back: 'തിരികെ', next: 'അടുത്തത്', previous: 'മുമ്പത്തെ', continueLabel: 'തുടരുക', retry: 'വീണ്ടും ശ്രമിക്കുക', success: 'വിജയം', error: 'എന്തോ പിശക് സംഭവിച്ചു. വീണ്ടും ശ്രമിക്കുക.' },
  te: { addToCart: 'కార్ట్‌కు జోడించండి', buyNow: 'ఇప్పుడే కొనండి', viewDetails: 'వివరాలు', trackOrder: 'ఆర్డర్‌ను ట్రాక్ చేయండి', outOfStock: 'స్టాక్‌లో లేదు', lowStock: 'తక్కువ స్టాక్', clearFilters: 'ఫిల్టర్‌లను క్లియర్ చేయండి', noProductsFound: 'ఉత్పత్తులు కనుగొనబడలేదు', tryDifferentSearch: 'వేరే పదాన్ని ప్రయత్నించండి, లేదా స్పెల్లింగ్ తనిఖీ చేయండి.', loading: 'లోడ్ అవుతోంది...', submit: 'సమర్పించండి', cancel: 'రద్దు చేయండి', save: 'సేవ్ చేయండి', delete: 'తొలగించండి', edit: 'సవరించండి', confirm: 'నిర్ధారించండి', close: 'మూసివేయండి', back: 'వెనుకకు', next: 'తదుపరి', previous: 'మునుపటి', continueLabel: 'కొనసాగించండి', retry: 'మళ్ళీ ప్రయత్నించండి', success: 'విజయం', error: 'ఏదో తప్పు జరిగింది. దయచేసి మళ్ళీ ప్రయత్నించండి.' },
  kn: { addToCart: 'ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ', buyNow: 'ಈಗ ಖರೀದಿಸಿ', viewDetails: 'ವಿವರಗಳು', trackOrder: 'ಆರ್ಡರ್ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ', outOfStock: 'ಸ್ಟಾಕ್ ಇಲ್ಲ', lowStock: 'ಕಡಿಮೆ ಸ್ಟಾಕ್', clearFilters: 'ಫಿಲ್ಟರ್‌ಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ', noProductsFound: 'ಯಾವುದೇ ಉತ್ಪನ್ನಗಳು ಕಂಡುಬಂದಿಲ್ಲ', tryDifferentSearch: 'ಬೇರೆ ಪದವನ್ನು ಪ್ರಯತ್ನಿಸಿ, ಅಥವಾ ಕಾಗುಣಿತ ಪರಿಶೀಲಿಸಿ.', loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...', submit: 'ಸಲ್ಲಿಸಿ', cancel: 'ರದ್ದುಮಾಡಿ', save: 'ಉಳಿಸಿ', delete: 'ಅಳಿಸಿ', edit: 'ಸಂಪಾದಿಸಿ', confirm: 'ದೃಢೀಕರಿಸಿ', close: 'ಮುಚ್ಚಿ', back: 'ಹಿಂದೆ', next: 'ಮುಂದೆ', previous: 'ಹಿಂದಿನ', continueLabel: 'ಮುಂದುವರಿಸಿ', retry: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ', success: 'ಯಶಸ್ಸು', error: 'ಏನೋ ತಪ್ಪಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.' },
};

const wishlist = {
  en: { title: 'Your wishlist', empty: "Nothing saved yet - tap the heart on any product to add it here.", browsePlants: 'Browse plants' },
  ta: { title: 'உங்கள் விருப்பப்பட்டியல்', empty: 'இதுவரை எதுவும் சேமிக்கப்படவில்லை - எந்த தயாரிப்பிலும் இதயத்தை தட்டி இங்கே சேர்க்கவும்.', browsePlants: 'செடிகளை உலாவுக' },
  hi: { title: 'आपकी विशलिस्ट', empty: 'अभी तक कुछ भी सहेजा नहीं गया - किसी भी उत्पाद पर दिल पर टैप करके यहां जोड़ें।', browsePlants: 'पौधे देखें' },
  ml: { title: 'നിങ്ങളുടെ വിഷ്‌ലിസ്റ്റ്', empty: 'ഇതുവരെ ഒന്നും സേവ് ചെയ്തിട്ടില്ല - ഏതെങ്കിലും ഉൽപ്പന്നത്തിലെ ഹൃദയത്തിൽ ടാപ്പ് ചെയ്ത് ഇവിടെ ചേർക്കുക.', browsePlants: 'ചെടികൾ ബ്രൗസ് ചെയ്യുക' },
  te: { title: 'మీ విష్‌లిస్ట్', empty: 'ఇంకా ఏమీ సేవ్ చేయబడలేదు - ఏదైనా ఉత్పత్తిపై హృదయాన్ని నొక్కి ఇక్కడ జోడించండి.', browsePlants: 'మొక్కలను బ్రౌజ్ చేయండి' },
  kn: { title: 'ನಿಮ್ಮ ವಿಶ್‌ಲಿಸ್ಟ್', empty: 'ಇನ್ನೂ ಏನೂ ಉಳಿಸಲಾಗಿಲ್ಲ - ಯಾವುದೇ ಉತ್ಪನ್ನದ ಹೃದಯವನ್ನು ಟ್ಯಾಪ್ ಮಾಡಿ ಇಲ್ಲಿ ಸೇರಿಸಿ.', browsePlants: 'ಸಸ್ಯಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ' },
};

const filters = {
  en: { filter: 'Filter', products: 'products', clearAll: 'Clear All', showProducts: 'Show {n} Products', selectedFilters: 'Selected Filters', showMore: 'Show More', showLess: 'Show Less', closeFilters: 'Close filters', from: 'From', to: 'To', clear: 'Clear', apply: 'Apply' },
  ta: { filter: 'வடிகட்டி', products: 'தயாரிப்புகள்', clearAll: 'அனைத்தையும் அழி', showProducts: '{n} தயாரிப்புகளைக் காட்டு', selectedFilters: 'தேர்ந்தெடுக்கப்பட்ட வடிகட்டிகள்', showMore: 'மேலும் காட்டு', showLess: 'குறைவாகக் காட்டு', closeFilters: 'வடிகட்டிகளை மூடு', from: 'இருந்து', to: 'வரை', clear: 'அழி', apply: 'பயன்படுத்து' },
  hi: { filter: 'फ़िल्टर', products: 'उत्पाद', clearAll: 'सभी हटाएं', showProducts: '{n} उत्पाद दिखाएं', selectedFilters: 'चयनित फ़िल्टर', showMore: 'और दिखाएं', showLess: 'कम दिखाएं', closeFilters: 'फ़िल्टर बंद करें', from: 'से', to: 'तक', clear: 'हटाएं', apply: 'लागू करें' },
  ml: { filter: 'ഫിൽട്ടർ', products: 'ഉൽപ്പന്നങ്ങൾ', clearAll: 'എല്ലാം മായ്ക്കുക', showProducts: '{n} ഉൽപ്പന്നങ്ങൾ കാണിക്കുക', selectedFilters: 'തിരഞ്ഞെടുത്ത ഫിൽട്ടറുകൾ', showMore: 'കൂടുതൽ കാണിക്കുക', showLess: 'കുറച്ച് കാണിക്കുക', closeFilters: 'ഫിൽട്ടറുകൾ അടയ്ക്കുക', from: 'മുതൽ', to: 'വരെ', clear: 'മായ്ക്കുക', apply: 'പ്രയോഗിക്കുക' },
  te: { filter: 'ఫిల్టర్', products: 'ఉత్పత్తులు', clearAll: 'అన్నీ క్లియర్ చేయండి', showProducts: '{n} ఉత్పత్తులను చూపించు', selectedFilters: 'ఎంచుకున్న ఫిల్టర్‌లు', showMore: 'మరిన్ని చూపించు', showLess: 'తక్కువ చూపించు', closeFilters: 'ఫిల్టర్‌లను మూసివేయండి', from: 'నుండి', to: 'వరకు', clear: 'క్లియర్ చేయండి', apply: 'వర్తింపజేయండి' },
  kn: { filter: 'ಫಿಲ್ಟರ್', products: 'ಉತ್ಪನ್ನಗಳು', clearAll: 'ಎಲ್ಲವನ್ನೂ ತೆರವುಗೊಳಿಸಿ', showProducts: '{n} ಉತ್ಪನ್ನಗಳನ್ನು ತೋರಿಸಿ', selectedFilters: 'ಆಯ್ಕೆಮಾಡಿದ ಫಿಲ್ಟರ್‌ಗಳು', showMore: 'ಹೆಚ್ಚು ತೋರಿಸಿ', showLess: 'ಕಡಿಮೆ ತೋರಿಸಿ', closeFilters: 'ಫಿಲ್ಟರ್‌ಗಳನ್ನು ಮುಚ್ಚಿ', from: 'ಇಂದ', to: 'ವರೆಗೆ', clear: 'ತೆರವುಗೊಳಿಸಿ', apply: 'ಅನ್ವಯಿಸಿ' },
};

const home = {
  en: { exploreEyebrow: 'EXPLORE', shopByCategory: 'Shop by category', shopByCategorySub: 'Everything you need to bring your garden to life', explore: 'Explore →', lovedEyebrow: 'LOVED BY OUR GARDENERS', plantsPeopleLove: 'Plants people love', seeAll: 'See all →', buildYourGarden: 'Build your garden →', beyondProducts: 'BEYOND PRODUCTS', gardenServices: 'Garden Services', learnMore: 'Learn more →', ourProcess: 'OUR PROCESS', journeyHeading: "From IGO Nursery to Your Home", journeySub: "Every plant's journey, start to finish.", whyIgoEyebrow: 'WHY IGO NURSERY', whyIgoHeading: 'Grown with data, delivered with care', discoverMore: 'Discover More', plantFinderEyebrow: 'PLANT FINDER', plantFinderHeading: 'Not sure where to begin?', findMyPlant: 'Find my plant', learnGrowThrive: 'LEARN • GROW • THRIVE', gardenJournal: 'Garden journal', readGuide: 'Read guide →', customerReviews: 'Customer reviews', supportEyebrow: 'SUPPORT', faqHeading: "We've probably answered it already", newsletterHeading: 'Get growing tips in your inbox.', newsletterPlaceholder: 'you@example.com', subscribe: 'SUBSCRIBE' },
  ta: { exploreEyebrow: 'ஆராயுங்கள்', shopByCategory: 'வகை வாரியாக வாங்குங்கள்', shopByCategorySub: 'உங்கள் தோட்டத்தை உயிர்ப்பிக்க தேவையான அனைத்தும்', explore: 'ஆராயுங்கள் →', lovedEyebrow: 'எங்கள் தோட்டக்காரர்களால் விரும்பப்படுகிறது', plantsPeopleLove: 'மக்கள் விரும்பும் செடிகள்', seeAll: 'அனைத்தையும் காண்க →', buildYourGarden: 'உங்கள் தோட்டத்தை உருவாக்குங்கள் →', beyondProducts: 'தயாரிப்புகளுக்கு அப்பால்', gardenServices: 'தோட்ட சேவைகள்', learnMore: 'மேலும் அறிக →', ourProcess: 'எங்கள் செயல்முறை', journeyHeading: 'IGO நர்சரியிலிருந்து உங்கள் வீடு வரை', journeySub: 'ஒவ்வொரு செடியின் பயணமும், தொடக்கம் முதல் முடிவு வரை.', whyIgoEyebrow: 'ஏன் IGO நர்சரி', whyIgoHeading: 'தரவுகளுடன் வளர்க்கப்பட்டு, அக்கறையுடன் வழங்கப்படுகிறது', discoverMore: 'மேலும் கண்டறியவும்', plantFinderEyebrow: 'செடி கண்டுபிடிப்பான்', plantFinderHeading: 'எங்கிருந்து தொடங்குவது எனத் தெரியவில்லையா?', findMyPlant: 'எனது செடியைக் கண்டறியவும்', learnGrowThrive: 'கற்றுக்கொள் • வளர் • செழிக்க', gardenJournal: 'தோட்ட பத்திரிகை', readGuide: 'வழிகாட்டியைப் படிக்கவும் →', customerReviews: 'வாடிக்கையாளர் விமர்சனங்கள்', supportEyebrow: 'ஆதரவு', faqHeading: 'நாங்கள் ஏற்கனவே பதிலளித்திருக்கலாம்', newsletterHeading: 'உங்கள் இன்பாக்ஸில் வளர்ப்பு குறிப்புகளைப் பெறுங்கள்.', newsletterPlaceholder: 'you@example.com', subscribe: 'குழுசேரு' },
  hi: { exploreEyebrow: 'एक्सप्लोर करें', shopByCategory: 'श्रेणी अनुसार खरीदें', shopByCategorySub: 'आपके बगीचे को जीवंत बनाने के लिए हर ज़रूरत की चीज़', explore: 'एक्सप्लोर करें →', lovedEyebrow: 'हमारे बागवानों द्वारा पसंद किया गया', plantsPeopleLove: 'लोगों के पसंदीदा पौधे', seeAll: 'सभी देखें →', buildYourGarden: 'अपना बगीचा बनाएं →', beyondProducts: 'उत्पादों से परे', gardenServices: 'बागवानी सेवाएं', learnMore: 'और जानें →', ourProcess: 'हमारी प्रक्रिया', journeyHeading: 'IGO नर्सरी से आपके घर तक', journeySub: 'हर पौधे की यात्रा, शुरुआत से अंत तक।', whyIgoEyebrow: 'IGO नर्सरी क्यों', whyIgoHeading: 'डेटा के साथ उगाया गया, देखभाल के साथ पहुंचाया गया', discoverMore: 'और जानें', plantFinderEyebrow: 'प्लांट फाइंडर', plantFinderHeading: 'शुरुआत कहाँ से करें, समझ नहीं आ रहा?', findMyPlant: 'मेरा पौधा खोजें', learnGrowThrive: 'सीखें • उगाएं • फलें-फूलें', gardenJournal: 'गार्डन जर्नल', readGuide: 'गाइड पढ़ें →', customerReviews: 'ग्राहक समीक्षाएं', supportEyebrow: 'सहायता', faqHeading: 'हमने शायद पहले ही इसका जवाब दे दिया है', newsletterHeading: 'अपने इनबॉक्स में उगाने के टिप्स पाएं।', newsletterPlaceholder: 'you@example.com', subscribe: 'सब्सक्राइब करें' },
  ml: { exploreEyebrow: 'പര്യവേക്ഷണം ചെയ്യുക', shopByCategory: 'വിഭാഗം അനുസരിച്ച് ഷോപ്പ് ചെയ്യുക', shopByCategorySub: 'നിങ്ങളുടെ തോട്ടത്തെ ജീവസുറ്റതാക്കാൻ വേണ്ടതെല്ലാം', explore: 'പര്യവേക്ഷണം ചെയ്യുക →', lovedEyebrow: 'ഞങ്ങളുടെ തോട്ടക്കാർ ഇഷ്ടപ്പെടുന്നത്', plantsPeopleLove: 'ആളുകൾ ഇഷ്ടപ്പെടുന്ന ചെടികൾ', seeAll: 'എല്ലാം കാണുക →', buildYourGarden: 'നിങ്ങളുടെ തോട്ടം നിർമ്മിക്കുക →', beyondProducts: 'ഉൽപ്പന്നങ്ങൾക്കപ്പുറം', gardenServices: 'തോട്ട സേവനങ്ങൾ', learnMore: 'കൂടുതൽ അറിയുക →', ourProcess: 'ഞങ്ങളുടെ പ്രക്രിയ', journeyHeading: 'IGO നഴ്സറിയിൽ നിന്ന് നിങ്ങളുടെ വീട്ടിലേക്ക്', journeySub: 'ഓരോ ചെടിയുടെയും യാത്ര, തുടക്കം മുതൽ അവസാനം വരെ.', whyIgoEyebrow: 'എന്തുകൊണ്ട് IGO നഴ്സറി', whyIgoHeading: 'ഡാറ്റയോടെ വളർത്തി, കരുതലോടെ എത്തിക്കുന്നു', discoverMore: 'കൂടുതൽ കണ്ടെത്തുക', plantFinderEyebrow: 'പ്ലാന്റ് ഫൈൻഡർ', plantFinderHeading: 'എവിടെ തുടങ്ങണമെന്ന് അറിയില്ലേ?', findMyPlant: 'എന്റെ ചെടി കണ്ടെത്തുക', learnGrowThrive: 'പഠിക്കുക • വളരുക • തഴച്ചുവളരുക', gardenJournal: 'ഗാർഡൻ ജേണൽ', readGuide: 'ഗൈഡ് വായിക്കുക →', customerReviews: 'ഉപഭോക്തൃ അവലോകനങ്ങൾ', supportEyebrow: 'പിന്തുണ', faqHeading: 'ഞങ്ങൾ ഇതിനകം ഉത്തരം നൽകിയിരിക്കാം', newsletterHeading: 'നിങ്ങളുടെ ഇൻബോക്സിൽ വളർത്തൽ നുറുങ്ങുകൾ നേടുക.', newsletterPlaceholder: 'you@example.com', subscribe: 'സബ്സ്ക്രൈബ് ചെയ്യുക' },
  te: { exploreEyebrow: 'అన్వేషించండి', shopByCategory: 'కేటగిరీ ద్వారా షాప్ చేయండి', shopByCategorySub: 'మీ తోటను జీవం పోసేందుకు అవసరమైనవన్నీ', explore: 'అన్వేషించండి →', lovedEyebrow: 'మా తోటమాలుల ఇష్టమైనది', plantsPeopleLove: 'ప్రజలు ఇష్టపడే మొక్కలు', seeAll: 'అన్నీ చూడండి →', buildYourGarden: 'మీ తోటను నిర్మించండి →', beyondProducts: 'ఉత్పత్తులకు అతీతంగా', gardenServices: 'తోట సేవలు', learnMore: 'మరింత తెలుసుకోండి →', ourProcess: 'మా ప్రక్రియ', journeyHeading: 'IGO నర్సరీ నుండి మీ ఇంటికి', journeySub: 'ప్రతి మొక్క ప్రయాణం, ప్రారంభం నుండి ముగింపు వరకు.', whyIgoEyebrow: 'IGO నర్సరీ ఎందుకు', whyIgoHeading: 'డేటాతో పెంచబడి, శ్రద్ధతో అందించబడుతుంది', discoverMore: 'మరింత కనుగొనండి', plantFinderEyebrow: 'ప్లాంట్ ఫైండర్', plantFinderHeading: 'ఎక్కడ ప్రారంభించాలో తెలియదా?', findMyPlant: 'నా మొక్కను కనుగొనండి', learnGrowThrive: 'నేర్చుకోండి • పెంచండి • వర్ధిల్లండి', gardenJournal: 'గార్డెన్ జర్నల్', readGuide: 'గైడ్ చదవండి →', customerReviews: 'కస్టమర్ సమీక్షలు', supportEyebrow: 'మద్దతు', faqHeading: 'మేము ఇప్పటికే దానికి సమాధానం ఇచ్చి ఉండవచ్చు', newsletterHeading: 'మీ ఇన్‌బాక్స్‌లో పెంపకం చిట్కాలు పొందండి.', newsletterPlaceholder: 'you@example.com', subscribe: 'సబ్‌స్క్రైబ్ చేయండి' },
  kn: { exploreEyebrow: 'ಅನ್ವೇಷಿಸಿ', shopByCategory: 'ವರ್ಗದ ಮೂಲಕ ಶಾಪಿಂಗ್ ಮಾಡಿ', shopByCategorySub: 'ನಿಮ್ಮ ತೋಟವನ್ನು ಜೀವಂತಗೊಳಿಸಲು ಬೇಕಾದ ಎಲ್ಲವೂ', explore: 'ಅನ್ವೇಷಿಸಿ →', lovedEyebrow: 'ನಮ್ಮ ತೋಟಗಾರರಿಂದ ಇಷ್ಟಪಡಲಾಗಿದೆ', plantsPeopleLove: 'ಜನರು ಇಷ್ಟಪಡುವ ಸಸ್ಯಗಳು', seeAll: 'ಎಲ್ಲಾ ನೋಡಿ →', buildYourGarden: 'ನಿಮ್ಮ ತೋಟವನ್ನು ನಿರ್ಮಿಸಿ →', beyondProducts: 'ಉತ್ಪನ್ನಗಳನ್ನು ಮೀರಿ', gardenServices: 'ತೋಟ ಸೇವೆಗಳು', learnMore: 'ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ →', ourProcess: 'ನಮ್ಮ ಪ್ರಕ್ರಿಯೆ', journeyHeading: 'IGO ನರ್ಸರಿಯಿಂದ ನಿಮ್ಮ ಮನೆಗೆ', journeySub: 'ಪ್ರತಿ ಸಸ್ಯದ ಪ್ರಯಾಣ, ಆರಂಭದಿಂದ ಅಂತ್ಯದವರೆಗೆ.', whyIgoEyebrow: 'ಏಕೆ IGO ನರ್ಸರಿ', whyIgoHeading: 'ಡೇಟಾದೊಂದಿಗೆ ಬೆಳೆಸಲಾಗಿದೆ, ಕಾಳಜಿಯಿಂದ ತಲುಪಿಸಲಾಗಿದೆ', discoverMore: 'ಇನ್ನಷ್ಟು ಅನ್ವೇಷಿಸಿ', plantFinderEyebrow: 'ಪ್ಲಾಂಟ್ ಫೈಂಡರ್', plantFinderHeading: 'ಎಲ್ಲಿಂದ ಪ್ರಾರಂಭಿಸಬೇಕೆಂದು ಖಚಿತವಿಲ್ಲವೇ?', findMyPlant: 'ನನ್ನ ಸಸ್ಯವನ್ನು ಹುಡುಕಿ', learnGrowThrive: 'ಕಲಿಯಿರಿ • ಬೆಳೆಸಿ • ಅಭಿವೃದ್ಧಿ ಹೊಂದಿ', gardenJournal: 'ಗಾರ್ಡನ್ ಜರ್ನಲ್', readGuide: 'ಗೈಡ್ ಓದಿ →', customerReviews: 'ಗ್ರಾಹಕ ವಿಮರ್ಶೆಗಳು', supportEyebrow: 'ಬೆಂಬಲ', faqHeading: 'ನಾವು ಈಗಾಗಲೇ ಅದಕ್ಕೆ ಉತ್ತರಿಸಿರಬಹುದು', newsletterHeading: 'ನಿಮ್ಮ ಇನ್‌ಬಾಕ್ಸ್‌ನಲ್ಲಿ ಬೆಳೆಸುವ ಸಲಹೆಗಳನ್ನು ಪಡೆಯಿರಿ.', newsletterPlaceholder: 'you@example.com', subscribe: 'ಚಂದಾದಾರರಾಗಿ' },
};

const offers = {
  en: { offersForYou: 'Offers For You', offersSub: 'Amazing deals to make your garden beautiful', buyAny: 'BUY ANY', shopNow: 'SHOP NOW →', buildBundle: 'BUILD YOUR OWN BUNDLE' },
  ta: { offersForYou: 'உங்களுக்கான சலுகைகள்', offersSub: 'உங்கள் தோட்டத்தை அழகாக்க அற்புதமான ஒப்பந்தங்கள்', buyAny: 'எதேனும் வாங்குங்கள்', shopNow: 'இப்போது வாங்குங்கள் →', buildBundle: 'உங்கள் சொந்த தொகுப்பை உருவாக்குங்கள்' },
  hi: { offersForYou: 'आपके लिए ऑफ़र', offersSub: 'आपके बगीचे को खूबसूरत बनाने के शानदार सौदे', buyAny: 'कोई भी खरीदें', shopNow: 'अभी खरीदें →', buildBundle: 'अपना बंडल बनाएं' },
  ml: { offersForYou: 'നിങ്ങൾക്കുള്ള ഓഫറുകൾ', offersSub: 'നിങ്ങളുടെ തോട്ടം മനോഹരമാക്കാൻ അതിശയകരമായ ഡീലുകൾ', buyAny: 'ഏതെങ്കിലും വാങ്ങുക', shopNow: 'ഇപ്പോൾ ഷോപ്പ് ചെയ്യുക →', buildBundle: 'നിങ്ങളുടെ സ്വന്തം ബണ്ടിൽ നിർമ്മിക്കുക' },
  te: { offersForYou: 'మీ కోసం ఆఫర్‌లు', offersSub: 'మీ తోటను అందంగా మార్చే అద్భుతమైన డీల్స్', buyAny: 'ఏదైనా కొనండి', shopNow: 'ఇప్పుడే షాప్ చేయండి →', buildBundle: 'మీ సొంత బండిల్‌ను నిర్మించండి' },
  kn: { offersForYou: 'ನಿಮಗಾಗಿ ಆಫರ್‌ಗಳು', offersSub: 'ನಿಮ್ಮ ತೋಟವನ್ನು ಸುಂದರಗೊಳಿಸುವ ಅದ್ಭುತ ಡೀಲ್‌ಗಳು', buyAny: 'ಯಾವುದಾದರೂ ಖರೀದಿಸಿ', shopNow: 'ಈಗ ಶಾಪಿಂಗ್ ಮಾಡಿ →', buildBundle: 'ನಿಮ್ಮ ಸ್ವಂತ ಬಂಡಲ್ ನಿರ್ಮಿಸಿ' },
};

// WHY_IGO card copy (matched by the array's `title`/`statLabel` key in
// Home.jsx, since the array itself stays the single source of truth for
// icon/order/featured-flag - only the display text is looked up here).
const whyIgo = {
  en: {
    titleIot: 'IoT-monitored nurseries', descIot: 'Every polyhouse tracks temperature, humidity and soil health in real time.',
    titlePrecision: 'Precision trials', descPrecision: 'New varieties are tested for months before they ever reach your cart.',
    titleGuarantee: 'health guarantee', descGuarantee: 'Plants leave the lab only when they clear our quality checks.',
    titleExpert: 'Expert plant-care guidance', descExpert: 'Free care notes and a support line for every plant you buy.',
    tagVerified: 'Verified',
  },
  ta: { titleIot: 'IoT-கண்காணிக்கப்படும் நர்சரிகள்', descIot: 'ஒவ்வொரு பாலிஹவுஸும் வெப்பநிலை, ஈரப்பதம் மற்றும் மண் ஆரோக்கியத்தை நேரடியாகக் கண்காணிக்கிறது.', titlePrecision: 'துல்லியமான சோதனைகள்', descPrecision: 'புதிய வகைகள் உங்கள் கார்ட்டை அடைவதற்கு முன் மாதக்கணக்கில் சோதிக்கப்படுகின்றன.', titleGuarantee: 'ஆரோக்கிய உத்தரவாதம்', descGuarantee: 'செடிகள் எங்கள் தர சோதனைகளில் தேர்ச்சி பெற்றால் மட்டுமே ஆய்வகத்தை விட்டு வெளியேறும்.', titleExpert: 'நிபுணர் செடி பராமரிப்பு வழிகாட்டுதல்', descExpert: 'நீங்கள் வாங்கும் ஒவ்வொரு செடிக்கும் இலவச பராமரிப்பு குறிப்புகள் மற்றும் ஆதரவு வரி.', tagVerified: 'சரிபார்க்கப்பட்டது' },
  hi: { titleIot: 'IoT-निगरानी वाली नर्सरी', descIot: 'हर पॉलीहाउस तापमान, नमी और मिट्टी के स्वास्थ्य को वास्तविक समय में ट्रैक करता है।', titlePrecision: 'सटीक परीक्षण', descPrecision: 'नई किस्मों को आपके कार्ट तक पहुंचने से पहले महीनों तक परखा जाता है।', titleGuarantee: 'स्वास्थ्य गारंटी', descGuarantee: 'पौधे तभी लैब छोड़ते हैं जब वे हमारी गुणवत्ता जांच पास करते हैं।', titleExpert: 'विशेषज्ञ पौध-देखभाल मार्गदर्शन', descExpert: 'आपके द्वारा खरीदे गए हर पौधे के लिए मुफ़्त देखभाल नोट्स और सहायता लाइन।', tagVerified: 'सत्यापित' },
  ml: { titleIot: 'IoT-നിരീക്ഷിത നഴ്സറികൾ', descIot: 'ഓരോ പോളിഹൗസും താപനില, ഈർപ്പം, മണ്ണിന്റെ ആരോഗ്യം എന്നിവ തത്സമയം ട്രാക്ക് ചെയ്യുന്നു.', titlePrecision: 'കൃത്യമായ പരീക്ഷണങ്ങൾ', descPrecision: 'പുതിയ ഇനങ്ങൾ നിങ്ങളുടെ കാർട്ടിലെത്തുന്നതിന് മുമ്പ് മാസങ്ങളോളം പരീക്ഷിക്കപ്പെടുന്നു.', titleGuarantee: 'ആരോഗ്യ ഉറപ്പ്', descGuarantee: 'ഞങ്ങളുടെ ഗുണനിലവാര പരിശോധനകൾ വിജയിക്കുമ്പോൾ മാത്രമേ ചെടികൾ ലാബ് വിടുകയുള്ളൂ.', titleExpert: 'വിദഗ്ദ്ധ ചെടി പരിചരണ മാർഗ്ഗനിർദ്ദേശം', descExpert: 'നിങ്ങൾ വാങ്ങുന്ന ഓരോ ചെടിക്കും സൗജന്യ പരിചരണ കുറിപ്പുകളും സപ്പോർട്ട് ലൈനും.', tagVerified: 'സ്ഥിരീകരിച്ചു' },
  te: { titleIot: 'IoT-పర్యవేక్షిత నర్సరీలు', descIot: 'ప్రతి పాలీహౌస్ ఉష్ణోగ్రత, తేమ మరియు నేల ఆరోగ్యాన్ని నిజ సమయంలో ట్రాక్ చేస్తుంది.', titlePrecision: 'ఖచ్చితమైన పరీక్షలు', descPrecision: 'కొత్త రకాలు మీ కార్ట్‌కు చేరే ముందు నెలల తరబడి పరీక్షించబడతాయి.', titleGuarantee: 'ఆరోగ్య హామీ', descGuarantee: 'మా నాణ్యత తనిఖీలలో ఉత్తీర్ణత సాధించినప్పుడే మొక్కలు ల్యాబ్‌ను వదిలివెళ్తాయి.', titleExpert: 'నిపుణుల మొక్కల సంరక్షణ మార్గదర్శకత్వం', descExpert: 'మీరు కొనుగోలు చేసే ప్రతి మొక్కకు ఉచిత సంరక్షణ గమనికలు మరియు సపోర్ట్ లైన్.', tagVerified: 'ధృవీకరించబడింది' },
  kn: { titleIot: 'IoT-ಮೇಲ್ವಿಚಾರಣೆಯ ನರ್ಸರಿಗಳು', descIot: 'ಪ್ರತಿ ಪಾಲಿಹೌಸ್ ತಾಪಮಾನ, ಆರ್ದ್ರತೆ ಮತ್ತು ಮಣ್ಣಿನ ಆರೋಗ್ಯವನ್ನು ನೈಜ ಸಮಯದಲ್ಲಿ ಟ್ರ್ಯಾಕ್ ಮಾಡುತ್ತದೆ.', titlePrecision: 'ನಿಖರವಾದ ಪ್ರಯೋಗಗಳು', descPrecision: 'ಹೊಸ ಪ್ರಭೇದಗಳು ನಿಮ್ಮ ಕಾರ್ಟ್ ತಲುಪುವ ಮೊದಲು ತಿಂಗಳುಗಟ್ಟಲೆ ಪರೀಕ್ಷಿಸಲ್ಪಡುತ್ತವೆ.', titleGuarantee: 'ಆರೋಗ್ಯ ಖಾತರಿ', descGuarantee: 'ನಮ್ಮ ಗುಣಮಟ್ಟ ಪರಿಶೀಲನೆಗಳಲ್ಲಿ ಉತ್ತೀರ್ಣರಾದಾಗ ಮಾತ್ರ ಸಸ್ಯಗಳು ಲ್ಯಾಬ್ ಬಿಡುತ್ತವೆ.', titleExpert: 'ತಜ್ಞ ಸಸ್ಯ ಆರೈಕೆ ಮಾರ್ಗದರ್ಶನ', descExpert: 'ನೀವು ಖರೀದಿಸುವ ಪ್ರತಿ ಸಸ್ಯಕ್ಕೂ ಉಚಿತ ಆರೈಕೆ ಟಿಪ್ಪಣಿಗಳು ಮತ್ತು ಬೆಂಬಲ ಲೈನ್.', tagVerified: 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ' },
};

const faq = {
  en: { qPackaging: 'How are plants packaged for delivery?', aPackaging: 'Every plant ships in a secure nursery pot with moisture-locking wrap and a care card, so it arrives ready to repot.', qGuarantee: 'Do you offer a health guarantee?', aGuarantee: 'Yes — if a plant arrives damaged or unhealthy, we replace it free within 7 days of delivery.', qHelp: 'Can I get gardening help after I buy?', aHelp: 'Every order includes access to our plant-care guidance line for as long as you own the plant.', qSeparate: 'Do you deliver pots and planters separately?', aSeparate: 'Yes, pots, seeds and tools can be ordered on their own or bundled with a plant.' },
  ta: { qPackaging: 'டெலிவரிக்கு செடிகள் எவ்வாறு பேக் செய்யப்படுகின்றன?', aPackaging: 'ஒவ்வொரு செடியும் ஈரப்பத தடுப்பு போர்வையுடன் பாதுகாப்பான நர்சரி பாட்டில் அனுப்பப்படுகிறது, ஒரு பராமரிப்பு அட்டையுடன், மறுநடவுக்குத் தயாராக வரும்.', qGuarantee: 'நீங்கள் ஆரோக்கிய உத்தரவாதம் வழங்குகிறீர்களா?', aGuarantee: 'ஆம் — ஒரு செடி சேதமடைந்த அல்லது ஆரோக்கியமற்ற நிலையில் வந்தால், டெலிவரி செய்த 7 நாட்களுக்குள் இலவசமாக மாற்றுகிறோம்.', qHelp: 'வாங்கிய பிறகு தோட்ட உதவி கிடைக்குமா?', aHelp: 'நீங்கள் செடியை வைத்திருக்கும் வரை ஒவ்வொரு ஆர்டரிலும் எங்கள் செடி பராமரிப்பு வழிகாட்டுதல் வரிக்கான அணுகல் அடங்கும்.', qSeparate: 'தொட்டிகள் மற்றும் பாட்களை தனியாக டெலிவரி செய்கிறீர்களா?', aSeparate: 'ஆம், தொட்டிகள், விதைகள் மற்றும் கருவிகளை தனியாகவோ அல்லது ஒரு செடியுடன் இணைத்தோ ஆர்டர் செய்யலாம்.' },
  hi: { qPackaging: 'डिलीवरी के लिए पौधों को कैसे पैक किया जाता है?', aPackaging: 'हर पौधा नमी-रोधी रैप और केयर कार्ड के साथ एक सुरक्षित नर्सरी पॉट में भेजा जाता है, ताकि यह रीपॉटिंग के लिए तैयार पहुंचे।', qGuarantee: 'क्या आप स्वास्थ्य गारंटी देते हैं?', aGuarantee: 'हां — अगर कोई पौधा क्षतिग्रस्त या अस्वस्थ पहुंचता है, तो हम डिलीवरी के 7 दिनों के भीतर इसे मुफ़्त में बदल देते हैं।', qHelp: 'क्या खरीदने के बाद बागवानी सहायता मिल सकती है?', aHelp: 'हर ऑर्डर में हमारी पौध-देखभाल मार्गदर्शन लाइन तक पहुंच शामिल है, जब तक आपके पास वह पौधा है।', qSeparate: 'क्या आप गमले और प्लांटर अलग से डिलीवर करते हैं?', aSeparate: 'हां, गमले, बीज और उपकरण अकेले या किसी पौधे के साथ बंडल करके ऑर्डर किए जा सकते हैं।' },
  ml: { qPackaging: 'ഡെലിവറിക്കായി ചെടികൾ എങ്ങനെ പാക്ക് ചെയ്യുന്നു?', aPackaging: 'ഓരോ ചെടിയും ഈർപ്പം-പൂട്ടുന്ന റാപ്പും കെയർ കാർഡുമായി സുരക്ഷിതമായ നഴ്സറി പോട്ടിൽ അയക്കുന്നു, അതിനാൽ ഇത് റീപോട്ട് ചെയ്യാൻ തയ്യാറായി എത്തുന്നു.', qGuarantee: 'നിങ്ങൾ ആരോഗ്യ ഉറപ്പ് നൽകുന്നുണ്ടോ?', aGuarantee: 'അതെ — ഒരു ചെടി കേടായോ ആരോഗ്യമില്ലാതെയോ എത്തിയാൽ, ഡെലിവറി കഴിഞ്ഞ് 7 ദിവസത്തിനുള്ളിൽ ഞങ്ങൾ സൗജന്യമായി മാറ്റിനൽകും.', qHelp: 'വാങ്ങിയ ശേഷം തോട്ട സഹായം ലഭിക്കുമോ?', aHelp: 'നിങ്ങൾ ചെടി കൈവശം വയ്ക്കുന്നിടത്തോളം ഓരോ ഓർഡറിലും ഞങ്ങളുടെ ചെടി പരിചരണ മാർഗ്ഗനിർദ്ദേശ ലൈനിലേക്കുള്ള ആക്സസ് ഉൾപ്പെടുന്നു.', qSeparate: 'ചട്ടികളും പ്ലാന്ററുകളും പ്രത്യേകം ഡെലിവർ ചെയ്യുമോ?', aSeparate: 'അതെ, ചട്ടികൾ, വിത്തുകൾ, ഉപകരണങ്ങൾ എന്നിവ ഒറ്റയ്ക്കോ ഒരു ചെടിയോടൊപ്പം ബണ്ടിൽ ചെയ്തോ ഓർഡർ ചെയ്യാം.' },
  te: { qPackaging: 'డెలివరీ కోసం మొక్కలు ఎలా ప్యాక్ చేయబడతాయి?', aPackaging: 'ప్రతి మొక్క తేమ-లాకింగ్ ర్యాప్ మరియు కేర్ కార్డుతో సురక్షితమైన నర్సరీ కుండలో పంపబడుతుంది, కాబట్టి ఇది రీపాటింగ్‌కు సిద్ధంగా వస్తుంది.', qGuarantee: 'మీరు ఆరోగ్య హామీ అందిస్తారా?', aGuarantee: 'అవును — ఒక మొక్క దెబ్బతిన్న లేదా ఆరోగ్యంగా లేని స్థితిలో వస్తే, డెలివరీ చేసిన 7 రోజుల్లోపు మేము దానిని ఉచితంగా మార్చుతాము.', qHelp: 'కొనుగోలు చేసిన తర్వాత తోటపని సహాయం పొందవచ్చా?', aHelp: 'మీరు మొక్కను కలిగి ఉన్నంత కాలం ప్రతి ఆర్డర్‌లో మా మొక్కల సంరక్షణ మార్గదర్శక లైన్‌కు యాక్సెస్ ఉంటుంది.', qSeparate: 'మీరు కుండలు మరియు ప్లాంటర్‌లను విడిగా డెలివరీ చేస్తారా?', aSeparate: 'అవును, కుండలు, విత్తనాలు మరియు పనిముట్లను విడిగా లేదా మొక్కతో కలిపి ఆర్డర్ చేయవచ్చు.' },
  kn: { qPackaging: 'ಡೆಲಿವರಿಗಾಗಿ ಸಸ್ಯಗಳನ್ನು ಹೇಗೆ ಪ್ಯಾಕ್ ಮಾಡಲಾಗುತ್ತದೆ?', aPackaging: 'ಪ್ರತಿ ಸಸ್ಯವನ್ನು ತೇವಾಂಶ-ಲಾಕಿಂಗ್ ರಾಪ್ ಮತ್ತು ಕೇರ್ ಕಾರ್ಡ್‌ನೊಂದಿಗೆ ಸುರಕ್ಷಿತ ನರ್ಸರಿ ಪಾಟ್‌ನಲ್ಲಿ ಕಳುಹಿಸಲಾಗುತ್ತದೆ, ಆದ್ದರಿಂದ ಇದು ಮರುನೆಡಲು ಸಿದ್ಧವಾಗಿ ಬರುತ್ತದೆ.', qGuarantee: 'ನೀವು ಆರೋಗ್ಯ ಖಾತರಿ ನೀಡುತ್ತೀರಾ?', aGuarantee: 'ಹೌದು — ಒಂದು ಸಸ್ಯ ಹಾನಿಗೊಳಗಾದ ಅಥವಾ ಅನಾರೋಗ್ಯಕರ ಸ್ಥಿತಿಯಲ್ಲಿ ಬಂದರೆ, ಡೆಲಿವರಿಯ 7 ದಿನಗಳಲ್ಲಿ ನಾವು ಅದನ್ನು ಉಚಿತವಾಗಿ ಬದಲಾಯಿಸುತ್ತೇವೆ.', qHelp: 'ಖರೀದಿಸಿದ ನಂತರ ತೋಟಗಾರಿಕೆ ಸಹಾಯ ಪಡೆಯಬಹುದೇ?', aHelp: 'ನೀವು ಸಸ್ಯವನ್ನು ಹೊಂದಿರುವವರೆಗೆ ಪ್ರತಿ ಆರ್ಡರ್‌ನಲ್ಲಿ ನಮ್ಮ ಸಸ್ಯ ಆರೈಕೆ ಮಾರ್ಗದರ್ಶನ ಲೈನ್‌ಗೆ ಪ್ರವೇಶ ಸೇರಿದೆ.', qSeparate: 'ನೀವು ಪಾಟ್‌ಗಳು ಮತ್ತು ಪ್ಲಾಂಟರ್‌ಗಳನ್ನು ಪ್ರತ್ಯೇಕವಾಗಿ ಡೆಲಿವರಿ ಮಾಡುತ್ತೀರಾ?', aSeparate: 'ಹೌದು, ಪಾಟ್‌ಗಳು, ಬೀಜಗಳು ಮತ್ತು ಉಪಕರಣಗಳನ್ನು ಒಂಟಿಯಾಗಿ ಅಥವಾ ಸಸ್ಯದೊಂದಿಗೆ ಬಂಡಲ್ ಮಾಡಿ ಆರ್ಡರ್ ಮಾಡಬಹುದು.' },
};

function merge(section) {
  const out = {};
  for (const code of LANGUAGES.map((l) => l.code)) out[code] = section[code] ?? section.en;
  return out;
}

const bySection = { nav, search, header, notifications, footer, cart, auth, checkout, orders, common, wishlist, product, filters, home, offers, whyIgo, faq };

export const translations = {};
for (const code of LANGUAGES.map((l) => l.code)) {
  translations[code] = {};
  for (const [sectionName, sectionDict] of Object.entries(bySection)) {
    translations[code][sectionName] = merge(sectionDict)[code];
  }
}

export function getTranslation(lang, path) {
  const dict = translations[lang] ?? translations.en;
  const value = path.split('.').reduce((acc, key) => acc?.[key], dict);
  if (value !== undefined && value !== null) return value;
  // Fall back to English for any key not yet translated (never show
  // "undefined", a raw key, or a blank string).
  const fallback = path.split('.').reduce((acc, key) => acc?.[key], translations.en);
  return fallback !== undefined && fallback !== null ? fallback : path;
}
